version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees: ["maintainer"]
  - package-ecosystem: "npm"
    directory: "/pacta_appweb"
    schedule:
      interval: "weekly"
    assignees: ["maintainer"]
