package ai

import (
	"bytes"
	"os"
	"testing"
)

// minimalPDF generates a minimal 1-page PDF in memory.
// Uses the simplest valid PDF structure (1.4, 1 object, empty page).
// This is only used if testdata/sample.pdf does not exist.
func minimalPDF() []byte {
	// A tiny valid PDF (generated by hand). Contains "Hello World" text.
	// This is a pre-built minimal PDF to avoid external dependencies in test.
	return []byte(`%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 72 72]/Parent 2 0 R/Resources<<>>>>/Contents 4 0 R>>endobj
4 0 obj<</Length 44>>stream
BT/F1 12 Tf 0 0 Td(Hello World)Tj ET
endstream
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f\r
0000000009 00000 n\r
0000000058 00000 n\r
0000000115 00000 n\r
0000000272 00000 n\r
0000000383 00000 n\r
trailer<</Size 5/Root 1 0 R>>
startxref
452
%%EOF`)
}

func TestExtractTextFromPDF(t *testing.T) {
	fixturePath := "internal/ai/testdata/sample.pdf"
	data, err := os.ReadFile(fixturePath)
	if os.IsNotExist(err) {
		// Autonomous fallback: generate minimal PDF in-memory
		t.Log("testdata/sample.pdf not found — using autonomous minimal PDF fixture")
		data = minimalPDF()
	} else if err != nil {
		t.Fatalf("failed to read fixture: %v", err)
	}

	text, err := ExtractTextFromPDF(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("extraction failed: %v", err)
	}
	if len(text) == 0 {
		t.Error("extracted text is empty")
	}
	// Should contain "Hello" from our minimal PDF or real content
	if len(text) < 5 {
		t.Error("extracted text suspiciously short:", text)
	}
}
