// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_legal.sql

package db

import (
	"context"
	"database/sql"
)

const countLegalDocuments = `-- name: CountLegalDocuments :one
SELECT COUNT(*) FROM legal_documents
WHERE deleted_at IS NULL
`

func (q *Queries) CountLegalDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLegalDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLegalChatMessage = `-- name: CreateLegalChatMessage :one

INSERT INTO ai_legal_chat_history (
  user_id, session_id, message_type, content,
  context_documents, metadata, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
)
RETURNING id, user_id, session_id, message_type, content, context_documents, metadata, created_at
`

type CreateLegalChatMessageParams struct {
	UserID           int64
	SessionID        string
	MessageType      string
	Content          string
	ContextDocuments sql.NullString
	Metadata         sql.NullString
}

// ========== ai_legal_chat_history ==========
// Note: ai_legal_chat_history does NOT have deleted_at (chat history)
func (q *Queries) CreateLegalChatMessage(ctx context.Context, arg CreateLegalChatMessageParams) (AiLegalChatHistory, error) {
	row := q.db.QueryRowContext(ctx, createLegalChatMessage,
		arg.UserID,
		arg.SessionID,
		arg.MessageType,
		arg.Content,
		arg.ContextDocuments,
		arg.Metadata,
	)
	var i AiLegalChatHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.MessageType,
		&i.Content,
		&i.ContextDocuments,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createLegalDocument = `-- name: CreateLegalDocument :one


INSERT INTO legal_documents (
  title, document_type, source, content, content_hash,
  language, jurisdiction, effective_date, publication_date,
  gaceta_number, tags, chunk_count, indexed_at,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, title, document_type, source, source_filename, content, content_text, content_hash, language, jurisdiction, effective_date, publication_date, gaceta_number, reference_number, tags, chunk_count, chunk_config, is_indexed, mime_type, size_bytes, storage_path, company_id, uploaded_by, indexed_at, created_at, updated_at, deleted_at
`

type CreateLegalDocumentParams struct {
	Title           string
	DocumentType    string
	Source          sql.NullString
	Content         string
	ContentHash     string
	Language        sql.NullString
	Jurisdiction    sql.NullString
	EffectiveDate   sql.NullTime
	PublicationDate sql.NullTime
	GacetaNumber    sql.NullString
	Tags            sql.NullString
	ChunkCount      sql.NullInt64
	IndexedAt       sql.NullTime
}

// ============================================================
// ai_legal queries (legal_documents + ai_legal_chat_history)
// ============================================================
// ========== legal_documents ==========
func (q *Queries) CreateLegalDocument(ctx context.Context, arg CreateLegalDocumentParams) (LegalDocument, error) {
	row := q.db.QueryRowContext(ctx, createLegalDocument,
		arg.Title,
		arg.DocumentType,
		arg.Source,
		arg.Content,
		arg.ContentHash,
		arg.Language,
		arg.Jurisdiction,
		arg.EffectiveDate,
		arg.PublicationDate,
		arg.GacetaNumber,
		arg.Tags,
		arg.ChunkCount,
		arg.IndexedAt,
	)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DocumentType,
		&i.Source,
		&i.SourceFilename,
		&i.Content,
		&i.ContentText,
		&i.ContentHash,
		&i.Language,
		&i.Jurisdiction,
		&i.EffectiveDate,
		&i.PublicationDate,
		&i.GacetaNumber,
		&i.ReferenceNumber,
		&i.Tags,
		&i.ChunkCount,
		&i.ChunkConfig,
		&i.IsIndexed,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CompanyID,
		&i.UploadedBy,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLegalChatSession = `-- name: DeleteLegalChatSession :exec
UPDATE ai_legal_chat_history
SET deleted_at = CURRENT_TIMESTAMP
WHERE session_id = ?
`

func (q *Queries) DeleteLegalChatSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteLegalChatSession, sessionID)
	return err
}

const deleteLegalDocument = `-- name: DeleteLegalDocument :exec
UPDATE legal_documents
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteLegalDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLegalDocument, id)
	return err
}

const getLastLegalDocumentIndexTime = `-- name: GetLastLegalDocumentIndexTime :one
SELECT MAX(indexed_at) FROM legal_documents
WHERE deleted_at IS NULL
`

func (q *Queries) GetLastLegalDocumentIndexTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLastLegalDocumentIndexTime)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getLegalChatHistoryBySession = `-- name: GetLegalChatHistoryBySession :many
SELECT id, user_id, session_id, message_type, content, context_documents, metadata, created_at FROM ai_legal_chat_history
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetLegalChatHistoryBySession(ctx context.Context, sessionID string) ([]AiLegalChatHistory, error) {
	rows, err := q.db.QueryContext(ctx, getLegalChatHistoryBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiLegalChatHistory
	for rows.Next() {
		var i AiLegalChatHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.MessageType,
			&i.Content,
			&i.ContextDocuments,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegalChatMessagesBySession = `-- name: GetLegalChatMessagesBySession :many
SELECT id, user_id, session_id, message_type, content, context_documents, metadata, created_at FROM ai_legal_chat_history
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetLegalChatMessagesBySession(ctx context.Context, sessionID string) ([]AiLegalChatHistory, error) {
	rows, err := q.db.QueryContext(ctx, getLegalChatMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiLegalChatHistory
	for rows.Next() {
		var i AiLegalChatHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.MessageType,
			&i.Content,
			&i.ContextDocuments,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegalChatSessionsByUser = `-- name: GetLegalChatSessionsByUser :many
SELECT
  session_id, user_id, MAX(created_at) as last_message,
  created_at, COUNT(*) as message_count
FROM ai_legal_chat_history
WHERE user_id = ?
GROUP BY session_id, user_id
ORDER BY last_message DESC
`

type GetLegalChatSessionsByUserRow struct {
	SessionID    string
	UserID       int64
	LastMessage  interface{}
	CreatedAt    sql.NullTime
	MessageCount int64
}

func (q *Queries) GetLegalChatSessionsByUser(ctx context.Context, userID int64) ([]GetLegalChatSessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegalChatSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegalChatSessionsByUserRow
	for rows.Next() {
		var i GetLegalChatSessionsByUserRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.LastMessage,
			&i.CreatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegalDocument = `-- name: GetLegalDocument :one
SELECT id, title, document_type, source, source_filename, content, content_text, content_hash, language, jurisdiction, effective_date, publication_date, gaceta_number, reference_number, tags, chunk_count, chunk_config, is_indexed, mime_type, size_bytes, storage_path, company_id, uploaded_by, indexed_at, created_at, updated_at, deleted_at FROM legal_documents
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetLegalDocument(ctx context.Context, id int64) (LegalDocument, error) {
	row := q.db.QueryRowContext(ctx, getLegalDocument, id)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DocumentType,
		&i.Source,
		&i.SourceFilename,
		&i.Content,
		&i.ContentText,
		&i.ContentHash,
		&i.Language,
		&i.Jurisdiction,
		&i.EffectiveDate,
		&i.PublicationDate,
		&i.GacetaNumber,
		&i.ReferenceNumber,
		&i.Tags,
		&i.ChunkCount,
		&i.ChunkConfig,
		&i.IsIndexed,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CompanyID,
		&i.UploadedBy,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLegalDocuments = `-- name: ListLegalDocuments :many
SELECT id, title, document_type, source, source_filename, content, content_text, content_hash, language, jurisdiction, effective_date, publication_date, gaceta_number, reference_number, tags, chunk_count, chunk_config, is_indexed, mime_type, size_bytes, storage_path, company_id, uploaded_by, indexed_at, created_at, updated_at, deleted_at FROM legal_documents
WHERE jurisdiction = ? OR ? = ''
ORDER BY created_at DESC
`

type ListLegalDocumentsParams struct {
	Jurisdiction sql.NullString
	Column2      interface{}
}

func (q *Queries) ListLegalDocuments(ctx context.Context, arg ListLegalDocumentsParams) ([]LegalDocument, error) {
	rows, err := q.db.QueryContext(ctx, listLegalDocuments, arg.Jurisdiction, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegalDocument
	for rows.Next() {
		var i LegalDocument
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DocumentType,
			&i.Source,
			&i.SourceFilename,
			&i.Content,
			&i.ContentText,
			&i.ContentHash,
			&i.Language,
			&i.Jurisdiction,
			&i.EffectiveDate,
			&i.PublicationDate,
			&i.GacetaNumber,
			&i.ReferenceNumber,
			&i.Tags,
			&i.ChunkCount,
			&i.ChunkConfig,
			&i.IsIndexed,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.CompanyID,
			&i.UploadedBy,
			&i.IndexedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLegalDocumentIndexed = `-- name: UpdateLegalDocumentIndexed :exec
UPDATE legal_documents
SET indexed_at = CURRENT_TIMESTAMP, chunk_count = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateLegalDocumentIndexedParams struct {
	ChunkCount sql.NullInt64
	ID         int64
}

func (q *Queries) UpdateLegalDocumentIndexed(ctx context.Context, arg UpdateLegalDocumentIndexedParams) error {
	_, err := q.db.ExecContext(ctx, updateLegalDocumentIndexed, arg.ChunkCount, arg.ID)
	return err
}
