// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_rate_limits.sql

package db

import (
	"context"
	"database/sql"
)

const cleanupOldRateLimits = `-- name: CleanupOldRateLimits :exec
 DELETE FROM ai_rate_limits
 WHERE date < date('now', '-30 days')
`

func (q *Queries) CleanupOldRateLimits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupOldRateLimits)
	return err
}

const getRateLimitInfo = `-- name: GetRateLimitInfo :many
 SELECT company_id, count, date
 FROM ai_rate_limits
 WHERE company_id = ?
 ORDER BY date DESC
 LIMIT ?
`

type GetRateLimitInfoParams struct {
	CompanyID int64
	Limit     int64
}

type GetRateLimitInfoRow struct {
	CompanyID int64
	Count     sql.NullInt64
	Date      string
}

func (q *Queries) GetRateLimitInfo(ctx context.Context, arg GetRateLimitInfoParams) ([]GetRateLimitInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getRateLimitInfo, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRateLimitInfoRow
	for rows.Next() {
		var i GetRateLimitInfoRow
		if err := rows.Scan(&i.CompanyID, &i.Count, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayRateLimitCount = `-- name: GetTodayRateLimitCount :one
 SELECT COALESCE(SUM(count), 0) FROM ai_rate_limits
 WHERE company_id = ? AND date = date('now')
`

func (q *Queries) GetTodayRateLimitCount(ctx context.Context, companyID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTodayRateLimitCount, companyID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const incrementRateLimit = `-- name: IncrementRateLimit :one

INSERT INTO ai_rate_limits (company_id, date, count)
VALUES (?, ?, 1)
ON CONFLICT (company_id, date)
DO UPDATE SET count = count + 1
RETURNING count
`

type IncrementRateLimitParams struct {
	CompanyID int64
	Date      string
}

// ============================================================
// ai_rate_limits queries
// Note: This table does NOT have deleted_at (metrics/audit data)
// ============================================================
func (q *Queries) IncrementRateLimit(ctx context.Context, arg IncrementRateLimitParams) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, incrementRateLimit, arg.CompanyID, arg.Date)
	var count sql.NullInt64
	err := row.Scan(&count)
	return count, err
}

const incrementRateLimitCount = `-- name: IncrementRateLimitCount :exec
 INSERT INTO ai_rate_limits (company_id, date, count)
 VALUES (?, date('now'), 1)
`

func (q *Queries) IncrementRateLimitCount(ctx context.Context, companyID int64) error {
	_, err := q.db.ExecContext(ctx, incrementRateLimitCount, companyID)
	return err
}
