// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO audit_logs (user_id, action, entity_type, entity_id, previous_state, new_state, ip_address, company_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateAuditLogParams struct {
	UserID        sql.NullInt64
	Action        string
	EntityType    string
	EntityID      sql.NullInt64
	PreviousState sql.NullString
	NewState      sql.NullString
	IpAddress     sql.NullString
	CompanyID     sql.NullInt64
}

// ============================================================
// audit_logs queries
// Note: audit_logs table does NOT have deleted_at (audit trail)
// ============================================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.PreviousState,
		arg.NewState,
		arg.IpAddress,
		arg.CompanyID,
	)
	return err
}

const listAuditLogsByCompany = `-- name: ListAuditLogsByCompany :many
SELECT id, user_id, action, entity_type, entity_id, previous_state, new_state, ip_address, created_at
FROM audit_logs
WHERE company_id = ?
ORDER BY created_at DESC
LIMIT 100
`

type ListAuditLogsByCompanyRow struct {
	ID            int64
	UserID        sql.NullInt64
	Action        string
	EntityType    string
	EntityID      sql.NullInt64
	PreviousState sql.NullString
	NewState      sql.NullString
	IpAddress     sql.NullString
	CreatedAt     sql.NullTime
}

func (q *Queries) ListAuditLogsByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListAuditLogsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsByCompanyRow
	for rows.Next() {
		var i ListAuditLogsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PreviousState,
			&i.NewState,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByFilters = `-- name: ListAuditLogsByFilters :many
SELECT id, user_id, action, entity_type, entity_id, previous_state, new_state, ip_address, created_at
FROM audit_logs
WHERE company_id = ?
  AND (? = '' OR entity_type = ?)
  AND (? = 0 OR entity_id = ?)
  AND (? = 0 OR user_id = ?)
  AND (? = '' OR action = ?)
ORDER BY created_at DESC
LIMIT 100
`

type ListAuditLogsByFiltersParams struct {
	CompanyID  sql.NullInt64
	Column2    interface{}
	EntityType string
	Column4    interface{}
	EntityID   sql.NullInt64
	Column6    interface{}
	UserID     sql.NullInt64
	Column8    interface{}
	Action     string
}

type ListAuditLogsByFiltersRow struct {
	ID            int64
	UserID        sql.NullInt64
	Action        string
	EntityType    string
	EntityID      sql.NullInt64
	PreviousState sql.NullString
	NewState      sql.NullString
	IpAddress     sql.NullString
	CreatedAt     sql.NullTime
}

func (q *Queries) ListAuditLogsByFilters(ctx context.Context, arg ListAuditLogsByFiltersParams) ([]ListAuditLogsByFiltersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByFilters,
		arg.CompanyID,
		arg.Column2,
		arg.EntityType,
		arg.Column4,
		arg.EntityID,
		arg.Column6,
		arg.UserID,
		arg.Column8,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsByFiltersRow
	for rows.Next() {
		var i ListAuditLogsByFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PreviousState,
			&i.NewState,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
