// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorized_signers.sql

package db

import (
	"context"
	"database/sql"
)

const createSigner = `-- name: CreateSigner :one
INSERT INTO authorized_signers (
  company_id, company_type, first_name, last_name,
  position, phone, email, created_by, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, company_id, company_type, first_name, last_name, position, phone, email, created_by, created_at, updated_at, deleted_at
`

type CreateSignerParams struct {
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	CreatedBy   sql.NullInt64
}

func (q *Queries) CreateSigner(ctx context.Context, arg CreateSignerParams) (AuthorizedSigner, error) {
	row := q.db.QueryRowContext(ctx, createSigner,
		arg.CompanyID,
		arg.CompanyType,
		arg.FirstName,
		arg.LastName,
		arg.Position,
		arg.Phone,
		arg.Email,
		arg.CreatedBy,
	)
	var i AuthorizedSigner
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Phone,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSigner = `-- name: DeleteSigner :exec
UPDATE authorized_signers
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteSigner(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSigner, id)
	return err
}

const getSignerByID = `-- name: GetSignerByID :one

SELECT
  id, company_id, company_type, first_name, last_name,
  position, phone, email, created_at, updated_at
FROM authorized_signers
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetSignerByIDRow struct {
	ID          int64
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// ============================================================
// authorized_signers queries
// ============================================================
func (q *Queries) GetSignerByID(ctx context.Context, id int64) (GetSignerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSignerByID, id)
	var i GetSignerByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignerByIDWithCompany = `-- name: GetSignerByIDWithCompany :one
SELECT id, company_id, company_type, first_name, last_name, position, phone, email, created_at, updated_at
FROM authorized_signers
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetSignerByIDWithCompanyParams struct {
	ID        int64
	CompanyID int64
}

type GetSignerByIDWithCompanyRow struct {
	ID          int64
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) GetSignerByIDWithCompany(ctx context.Context, arg GetSignerByIDWithCompanyParams) (GetSignerByIDWithCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, getSignerByIDWithCompany, arg.ID, arg.CompanyID)
	var i GetSignerByIDWithCompanyRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignerCompanyOwnership = `-- name: GetSignerCompanyOwnership :one
SELECT company_id FROM authorized_signers
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetSignerCompanyOwnership(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSignerCompanyOwnership, id)
	var company_id int64
	err := row.Scan(&company_id)
	return company_id, err
}

const getSignerForAudit = `-- name: GetSignerForAudit :one
SELECT company_id, company_type, first_name, last_name, position, phone, email
FROM authorized_signers
WHERE id = ? AND deleted_at IS NULL
`

type GetSignerForAuditRow struct {
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
}

func (q *Queries) GetSignerForAudit(ctx context.Context, id int64) (GetSignerForAuditRow, error) {
	row := q.db.QueryRowContext(ctx, getSignerForAudit, id)
	var i GetSignerForAuditRow
	err := row.Scan(
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const getSignerForContractValidation = `-- name: GetSignerForContractValidation :one
SELECT a.company_id, a.company_type, a.first_name, a.last_name
FROM authorized_signers a
WHERE a.id = ? AND a.deleted_at IS NULL
  AND a.company_id IN (
    SELECT cl.id FROM clients cl WHERE cl.company_id = ? AND cl.deleted_at IS NULL
    UNION ALL
    SELECT s.id FROM suppliers s WHERE s.company_id = ? AND s.deleted_at IS NULL
  )
LIMIT 1
`

type GetSignerForContractValidationParams struct {
	ID          int64
	CompanyID   sql.NullInt64
	CompanyID_2 sql.NullInt64
}

type GetSignerForContractValidationRow struct {
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
}

func (q *Queries) GetSignerForContractValidation(ctx context.Context, arg GetSignerForContractValidationParams) (GetSignerForContractValidationRow, error) {
	row := q.db.QueryRowContext(ctx, getSignerForContractValidation, arg.ID, arg.CompanyID, arg.CompanyID_2)
	var i GetSignerForContractValidationRow
	err := row.Scan(
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getSignerWithValidation = `-- name: GetSignerWithValidation :one
SELECT a.id, a.company_id, a.company_type, a.first_name, a.last_name,
       a.position, a.phone, a.email, a.created_at, a.updated_at
FROM authorized_signers a
WHERE a.id = ? AND a.deleted_at IS NULL
  AND a.company_id IN (
    SELECT cl.id FROM clients cl WHERE cl.company_id = ? AND cl.deleted_at IS NULL
    UNION ALL
    SELECT s.id FROM suppliers s WHERE s.company_id = ? AND s.deleted_at IS NULL
  )
LIMIT 1
`

type GetSignerWithValidationParams struct {
	ID          int64
	CompanyID   sql.NullInt64
	CompanyID_2 sql.NullInt64
}

type GetSignerWithValidationRow struct {
	ID          int64
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) GetSignerWithValidation(ctx context.Context, arg GetSignerWithValidationParams) (GetSignerWithValidationRow, error) {
	row := q.db.QueryRowContext(ctx, getSignerWithValidation, arg.ID, arg.CompanyID, arg.CompanyID_2)
	var i GetSignerWithValidationRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSignersByClient = `-- name: ListSignersByClient :many
SELECT s.id, s.first_name, s.last_name, s.position, s.phone, s.email
FROM authorized_signers s
WHERE s.company_id = ? AND s.company_type = 'client'
  AND s.deleted_at IS NULL
ORDER BY s.last_name, s.first_name
`

type ListSignersByClientRow struct {
	ID        int64
	FirstName string
	LastName  string
	Position  sql.NullString
	Phone     sql.NullString
	Email     sql.NullString
}

func (q *Queries) ListSignersByClient(ctx context.Context, companyID int64) ([]ListSignersByClientRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignersByClient, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignersByClientRow
	for rows.Next() {
		var i ListSignersByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Position,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignersByCompany = `-- name: ListSignersByCompany :many
SELECT id, company_id, company_type, first_name, last_name, position, phone, email
FROM authorized_signers
WHERE company_id = ? AND deleted_at IS NULL
ORDER BY last_name, first_name
`

type ListSignersByCompanyRow struct {
	ID          int64
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
}

func (q *Queries) ListSignersByCompany(ctx context.Context, companyID int64) ([]ListSignersByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignersByCompanyRow
	for rows.Next() {
		var i ListSignersByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyType,
			&i.FirstName,
			&i.LastName,
			&i.Position,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignersByCompanyAndType = `-- name: ListSignersByCompanyAndType :many
SELECT id, company_id, company_type, first_name, last_name, position, phone, email
FROM authorized_signers
WHERE company_id = ? AND company_type = ? AND deleted_at IS NULL
ORDER BY last_name, first_name
`

type ListSignersByCompanyAndTypeParams struct {
	CompanyID   int64
	CompanyType string
}

type ListSignersByCompanyAndTypeRow struct {
	ID          int64
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
}

func (q *Queries) ListSignersByCompanyAndType(ctx context.Context, arg ListSignersByCompanyAndTypeParams) ([]ListSignersByCompanyAndTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignersByCompanyAndType, arg.CompanyID, arg.CompanyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignersByCompanyAndTypeRow
	for rows.Next() {
		var i ListSignersByCompanyAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyType,
			&i.FirstName,
			&i.LastName,
			&i.Position,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignersBySupplier = `-- name: ListSignersBySupplier :many
SELECT s.id, s.first_name, s.last_name, s.position, s.phone, s.email
FROM authorized_signers s
WHERE s.company_id = ? AND s.company_type = 'supplier'
  AND s.deleted_at IS NULL
ORDER BY s.last_name, s.first_name
`

type ListSignersBySupplierRow struct {
	ID        int64
	FirstName string
	LastName  string
	Position  sql.NullString
	Phone     sql.NullString
	Email     sql.NullString
}

func (q *Queries) ListSignersBySupplier(ctx context.Context, companyID int64) ([]ListSignersBySupplierRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignersBySupplier, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignersBySupplierRow
	for rows.Next() {
		var i ListSignersBySupplierRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Position,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const signerExists = `-- name: SignerExists :one
SELECT COUNT(*) FROM authorized_signers
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
`

type SignerExistsParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) SignerExists(ctx context.Context, arg SignerExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, signerExists, arg.ID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSigner = `-- name: UpdateSigner :one
UPDATE authorized_signers
SET
  company_id = ?, company_type = ?, first_name = ?, last_name = ?,
  position = ?, phone = ?, email = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, company_id, company_type, first_name, last_name, position, phone, email, created_by, created_at, updated_at, deleted_at
`

type UpdateSignerParams struct {
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	ID          int64
}

func (q *Queries) UpdateSigner(ctx context.Context, arg UpdateSignerParams) (AuthorizedSigner, error) {
	row := q.db.QueryRowContext(ctx, updateSigner,
		arg.CompanyID,
		arg.CompanyType,
		arg.FirstName,
		arg.LastName,
		arg.Position,
		arg.Phone,
		arg.Email,
		arg.ID,
	)
	var i AuthorizedSigner
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyType,
		&i.FirstName,
		&i.LastName,
		&i.Position,
		&i.Phone,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
