// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"
	"database/sql"
)

const clientExists = `-- name: ClientExists :one
SELECT COUNT(*) FROM clients
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type ClientExistsParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) ClientExists(ctx context.Context, arg ClientExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, clientExists, arg.ID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClientsByCompany = `-- name: CountClientsByCompany :one
SELECT COUNT(*) FROM clients
WHERE company_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountClientsByCompany(ctx context.Context, companyID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClientsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
  company_id, name, address, reu_code, contacts,
  created_by, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, name, address, reu_code, contacts, company_id, created_by, created_at, updated_at, deleted_at
`

type CreateClientParams struct {
	CompanyID sql.NullInt64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CreatedBy sql.NullInt64
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.CompanyID,
		arg.Name,
		arg.Address,
		arg.ReuCode,
		arg.Contacts,
		arg.CreatedBy,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
UPDATE clients
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type DeleteClientParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.ExecContext(ctx, deleteClient, arg.ID, arg.CompanyID)
	return err
}

const getClientByID = `-- name: GetClientByID :one

SELECT id, company_id, name, address, reu_code, contacts,
       created_by, created_at, updated_at
FROM clients
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetClientByIDRow struct {
	ID        int64
	CompanyID sql.NullInt64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

// ============================================================
// clients queries
// ============================================================
func (q *Queries) GetClientByID(ctx context.Context, id int64) (GetClientByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i GetClientByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByIDWithCompany = `-- name: GetClientByIDWithCompany :one
SELECT id, company_id, name, address, reu_code, contacts,
       created_by, created_at, updated_at
FROM clients
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetClientByIDWithCompanyParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

type GetClientByIDWithCompanyRow struct {
	ID        int64
	CompanyID sql.NullInt64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetClientByIDWithCompany(ctx context.Context, arg GetClientByIDWithCompanyParams) (GetClientByIDWithCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, getClientByIDWithCompany, arg.ID, arg.CompanyID)
	var i GetClientByIDWithCompanyRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientName = `-- name: GetClientName :one
SELECT name FROM clients
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetClientNameParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) GetClientName(ctx context.Context, arg GetClientNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getClientName, arg.ID, arg.CompanyID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listClientsByCompany = `-- name: ListClientsByCompany :many
SELECT id, name, address, reu_code, contacts
FROM clients
WHERE company_id = ? AND deleted_at IS NULL
ORDER BY name
`

type ListClientsByCompanyRow struct {
	ID       int64
	Name     string
	Address  sql.NullString
	ReuCode  sql.NullString
	Contacts sql.NullString
}

func (q *Queries) ListClientsByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListClientsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listClientsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsByCompanyRow
	for rows.Next() {
		var i ListClientsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ReuCode,
			&i.Contacts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = ?, address = ?, reu_code = ?, contacts = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
RETURNING id, name, address, reu_code, contacts, company_id, created_by, created_at, updated_at, deleted_at
`

type UpdateClientParams struct {
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.Name,
		arg.Address,
		arg.ReuCode,
		arg.Contacts,
		arg.ID,
		arg.CompanyID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
