// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
	"database/sql"
)

const countCompanies = `-- name: CountCompanies :one
SELECT COUNT(*) FROM companies
WHERE deleted_at IS NULL
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
  name, address, tax_id, company_type, parent_id,
  created_by, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, name, address, tax_id, company_type, parent_id, created_at, updated_at, deleted_at, created_by
`

type CreateCompanyParams struct {
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	CreatedBy   sql.NullInt64
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.Name,
		arg.Address,
		arg.TaxID,
		arg.CompanyType,
		arg.ParentID,
		arg.CreatedBy,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TaxID,
		&i.CompanyType,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createCompanySimple = `-- name: CreateCompanySimple :one
INSERT INTO companies (
  name, company_type, created_at, updated_at
) VALUES (
  ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, name, address, tax_id, company_type, parent_id, created_at, updated_at, deleted_at, created_by
`

type CreateCompanySimpleParams struct {
	Name        string
	CompanyType string
}

func (q *Queries) CreateCompanySimple(ctx context.Context, arg CreateCompanySimpleParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompanySimple, arg.Name, arg.CompanyType)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TaxID,
		&i.CompanyType,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
UPDATE companies
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteCompany(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompany, id)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, address, tax_id, company_type,
       parent_id, created_at, updated_at
FROM companies
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetCompanyByIDRow struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) GetCompanyByID(ctx context.Context, id int64) (GetCompanyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i GetCompanyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TaxID,
		&i.CompanyType,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyType = `-- name: GetCompanyType :one
SELECT company_type FROM companies
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCompanyType(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCompanyType, id)
	var company_type string
	err := row.Scan(&company_type)
	return company_type, err
}

const getCompanyTypeByID = `-- name: GetCompanyTypeByID :one
SELECT company_type FROM companies
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCompanyTypeByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCompanyTypeByID, id)
	var company_type string
	err := row.Scan(&company_type)
	return company_type, err
}

const getCompanyWithParent = `-- name: GetCompanyWithParent :one
SELECT c.id, c.name, c.address, c.tax_id, c.company_type, c.parent_id,
       p.name as parent_name, c.created_by, c.created_at, c.updated_at
FROM companies c
LEFT JOIN companies p ON c.parent_id = p.id
WHERE c.id = ? AND c.deleted_at IS NULL
LIMIT 1
`

type GetCompanyWithParentRow struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	ParentName  sql.NullString
	CreatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) GetCompanyWithParent(ctx context.Context, id int64) (GetCompanyWithParentRow, error) {
	row := q.db.QueryRowContext(ctx, getCompanyWithParent, id)
	var i GetCompanyWithParentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TaxID,
		&i.CompanyType,
		&i.ParentID,
		&i.ParentName,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubsidiaries = `-- name: GetSubsidiaries :many
SELECT id, name, company_type
FROM companies
WHERE parent_id = ? AND deleted_at IS NULL
ORDER BY name
`

type GetSubsidiariesRow struct {
	ID          int64
	Name        string
	CompanyType string
}

func (q *Queries) GetSubsidiaries(ctx context.Context, parentID sql.NullInt64) ([]GetSubsidiariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubsidiaries, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubsidiariesRow
	for rows.Next() {
		var i GetSubsidiariesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CompanyType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCompanies = `-- name: ListAllCompanies :many

SELECT c.id, c.name, c.address, c.tax_id, c.company_type, c.parent_id,
       p.name as parent_name, c.created_by, c.created_at, c.updated_at
FROM companies c
LEFT JOIN companies p ON c.parent_id = p.id
WHERE c.deleted_at IS NULL
ORDER BY c.company_type DESC, c.name
`

type ListAllCompaniesRow struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	ParentName  sql.NullString
	CreatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// ============================================================
// companies queries
// ============================================================
func (q *Queries) ListAllCompanies(ctx context.Context) ([]ListAllCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCompaniesRow
	for rows.Next() {
		var i ListAllCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TaxID,
			&i.CompanyType,
			&i.ParentID,
			&i.ParentName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCompaniesOrdered = `-- name: ListAllCompaniesOrdered :many
SELECT c.id, c.name, c.address, c.tax_id, c.company_type, c.parent_id,
       p.name as parent_name, c.created_by, c.created_at, c.updated_at
FROM companies c
LEFT JOIN companies p ON c.parent_id = p.id
WHERE c.deleted_at IS NULL
ORDER BY c.company_type DESC, c.name
`

type ListAllCompaniesOrderedRow struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	ParentName  sql.NullString
	CreatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) ListAllCompaniesOrdered(ctx context.Context) ([]ListAllCompaniesOrderedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCompaniesOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCompaniesOrderedRow
	for rows.Next() {
		var i ListAllCompaniesOrderedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TaxID,
			&i.CompanyType,
			&i.ParentID,
			&i.ParentName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, company_type, parent_id, created_at
FROM companies
WHERE deleted_at IS NULL
ORDER BY name
`

type ListCompaniesRow struct {
	ID          int64
	Name        string
	CompanyType string
	ParentID    sql.NullInt64
	CreatedAt   sql.NullTime
}

func (q *Queries) ListCompanies(ctx context.Context) ([]ListCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesRow
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CompanyType,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesForUser = `-- name: ListCompaniesForUser :many
SELECT c.id, c.name, c.address, c.tax_id, c.company_type, c.parent_id,
       p.name as parent_name, c.created_by, c.created_at, c.updated_at
FROM companies c
JOIN user_companies uc ON uc.company_id = c.id
LEFT JOIN companies p ON c.parent_id = p.id
WHERE uc.user_id = ? AND c.deleted_at IS NULL
ORDER BY c.company_type DESC, c.name
`

type ListCompaniesForUserRow struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	ParentName  sql.NullString
	CreatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) ListCompaniesForUser(ctx context.Context, userID int64) ([]ListCompaniesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesForUserRow
	for rows.Next() {
		var i ListCompaniesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TaxID,
			&i.CompanyType,
			&i.ParentID,
			&i.ParentName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCompanies = `-- name: ListUserCompanies :many
SELECT c.id, c.name, c.address, c.tax_id, c.company_type, c.parent_id,
       p.name as parent_name, c.created_by, c.created_at, c.updated_at
FROM companies c
JOIN user_companies uc ON uc.company_id = c.id
LEFT JOIN companies p ON c.parent_id = p.id
WHERE uc.user_id = ? AND c.deleted_at IS NULL
ORDER BY c.company_type DESC, c.name
`

type ListUserCompaniesRow struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	ParentName  sql.NullString
	CreatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) ListUserCompanies(ctx context.Context, userID int64) ([]ListUserCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserCompanies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCompaniesRow
	for rows.Next() {
		var i ListUserCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TaxID,
			&i.CompanyType,
			&i.ParentID,
			&i.ParentName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = ?, address = ?, tax_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, address, tax_id, company_type, parent_id, created_at, updated_at, deleted_at, created_by
`

type UpdateCompanyParams struct {
	Name    string
	Address sql.NullString
	TaxID   sql.NullString
	ID      int64
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.Name,
		arg.Address,
		arg.TaxID,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TaxID,
		&i.CompanyType,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}
