// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_expiry_log.sql

package db

import (
	"context"
	"database/sql"
)

const upsertNotificationLog = `-- name: UpsertNotificationLog :exec
INSERT INTO contract_expiry_notification_log
    (contract_id, threshold_days, sent_to_user, sent_to_admin, sent_at, delivery_status, error_message, channel)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (contract_id, threshold_days)
DO UPDATE SET
    sent_to_user = excluded.sent_to_user,
    sent_to_admin = excluded.sent_to_admin,
    sent_at = excluded.sent_at,
    delivery_status = excluded.delivery_status,
    error_message = excluded.error_message,
    channel = excluded.channel
`

type UpsertNotificationLogParams struct {
	ContractID     int64
	ThresholdDays  int64
	SentToUser     bool
	SentToAdmin    bool
	SentAt         sql.NullTime
	DeliveryStatus string
	ErrorMessage   sql.NullString
	Channel        string
}

func (q *Queries) UpsertNotificationLog(ctx context.Context, arg UpsertNotificationLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationLog,
		arg.ContractID,
		arg.ThresholdDays,
		arg.SentToUser,
		arg.SentToAdmin,
		arg.SentAt,
		arg.DeliveryStatus,
		arg.ErrorMessage,
		arg.Channel,
	)
	return err
}
