// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contracts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const contractExists = `-- name: ContractExists :one
SELECT COUNT(*) FROM contracts
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type ContractExistsParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) ContractExists(ctx context.Context, arg ContractExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, contractExists, arg.ID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveContracts = `-- name: CountActiveContracts :one
SELECT COUNT(*) FROM contracts
WHERE company_id = ? AND deleted_at IS NULL AND status = 'active'
`

func (q *Queries) CountActiveContracts(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveContracts, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContractsByCompany = `-- name: CountContractsByCompany :one
SELECT COUNT(*) FROM contracts
WHERE company_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountContractsByCompany(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContractsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (
  internal_id, contract_number, title, client_id, supplier_id,
  client_signer_id, supplier_signer_id, start_date, end_date,
  amount, type, status, description, object, fulfillment_place,
  dispute_resolution, has_confidentiality, guarantees, renewal_type,
  document_url, document_key, company_id, created_by, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, contract_number, title, client_id, supplier_id, client_signer_id, supplier_signer_id, start_date, end_date, amount, type, status, description, internal_id, company_id, object, fulfillment_place, dispute_resolution, has_confidentiality, guarantees, renewal_type, document_url, document_key, created_by, created_at, updated_at, deleted_at
`

type CreateContractParams struct {
	InternalID         string
	ContractNumber     string
	Title              sql.NullString
	ClientID           int64
	SupplierID         int64
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Type               string
	Status             string
	Description        sql.NullString
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	CompanyID          int64
	CreatedBy          sql.NullInt64
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, createContract,
		arg.InternalID,
		arg.ContractNumber,
		arg.Title,
		arg.ClientID,
		arg.SupplierID,
		arg.ClientSignerID,
		arg.SupplierSignerID,
		arg.StartDate,
		arg.EndDate,
		arg.Amount,
		arg.Type,
		arg.Status,
		arg.Description,
		arg.Object,
		arg.FulfillmentPlace,
		arg.DisputeResolution,
		arg.HasConfidentiality,
		arg.Guarantees,
		arg.RenewalType,
		arg.DocumentUrl,
		arg.DocumentKey,
		arg.CompanyID,
		arg.CreatedBy,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.InternalID,
		&i.CompanyID,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteContract = `-- name: DeleteContract :exec
UPDATE contracts
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type DeleteContractParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) DeleteContract(ctx context.Context, arg DeleteContractParams) error {
	_, err := q.db.ExecContext(ctx, deleteContract, arg.ID, arg.CompanyID)
	return err
}

const getActiveContracts = `-- name: GetActiveContracts :many
SELECT id, internal_id, contract_number, title, client_id, supplier_id,
       start_date, end_date, amount, type, status
FROM contracts
WHERE company_id = ? AND deleted_at IS NULL AND status = 'active'
ORDER BY end_date ASC
`

type GetActiveContractsRow struct {
	ID             int64
	InternalID     string
	ContractNumber string
	Title          sql.NullString
	ClientID       int64
	SupplierID     int64
	StartDate      time.Time
	EndDate        time.Time
	Amount         float64
	Type           string
	Status         string
}

func (q *Queries) GetActiveContracts(ctx context.Context, companyID int64) ([]GetActiveContractsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveContracts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveContractsRow
	for rows.Next() {
		var i GetActiveContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractNumber,
			&i.Title,
			&i.ClientID,
			&i.SupplierID,
			&i.StartDate,
			&i.EndDate,
			&i.Amount,
			&i.Type,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllContractIDsForRAG = `-- name: GetAllContractIDsForRAG :many
SELECT id FROM contracts WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) GetAllContractIDsForRAG(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllContractIDsForRAG)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientCompanyID = `-- name: GetClientCompanyID :one
SELECT company_id FROM clients
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetClientCompanyID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getClientCompanyID, id)
	var company_id sql.NullInt64
	err := row.Scan(&company_id)
	return company_id, err
}

const getContractByID = `-- name: GetContractByID :one

SELECT
  c.id, c.internal_id, c.contract_number, c.title,
  c.client_id, c.supplier_id, c.client_signer_id, c.supplier_signer_id,
  c.start_date, c.end_date, c.amount, c.type, c.status,
  c.description, c.object, c.fulfillment_place, c.dispute_resolution,
  c.has_confidentiality, c.guarantees, c.renewal_type,
  c.document_url, c.document_key,
  c.company_id, c.created_by, c.created_at, c.updated_at
FROM contracts c
WHERE c.id = ? AND c.deleted_at IS NULL AND c.company_id = ?
LIMIT 1
`

type GetContractByIDParams struct {
	ID        int64
	CompanyID int64
}

type GetContractByIDRow struct {
	ID                 int64
	InternalID         string
	ContractNumber     string
	Title              sql.NullString
	ClientID           int64
	SupplierID         int64
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Type               string
	Status             string
	Description        sql.NullString
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	CompanyID          int64
	CreatedBy          sql.NullInt64
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

// ============================================================
// contracts queries
// ============================================================
func (q *Queries) GetContractByID(ctx context.Context, arg GetContractByIDParams) (GetContractByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContractByID, arg.ID, arg.CompanyID)
	var i GetContractByIDRow
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractByInternalID = `-- name: GetContractByInternalID :one
SELECT id, contract_number, title, client_id, supplier_id, client_signer_id, supplier_signer_id, start_date, end_date, amount, type, status, description, internal_id, company_id, object, fulfillment_place, dispute_resolution, has_confidentiality, guarantees, renewal_type, document_url, document_key, created_by, created_at, updated_at, deleted_at FROM contracts
WHERE internal_id = ? AND company_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetContractByInternalIDParams struct {
	InternalID string
	CompanyID  int64
}

func (q *Queries) GetContractByInternalID(ctx context.Context, arg GetContractByInternalIDParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, getContractByInternalID, arg.InternalID, arg.CompanyID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.InternalID,
		&i.CompanyID,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContractForRAG = `-- name: GetContractForRAG :one
SELECT
  c.id, c.title, c.type, c.object, COALESCE(c.description, '') as content,
  COALESCE(cl.name, '') as client_name, COALESCE(s.name, '') as supplier_name,
  c.created_at
FROM contracts c
LEFT JOIN companies cl ON c.client_id = cl.id
LEFT JOIN companies s ON c.supplier_id = s.id
WHERE c.id = ? AND c.deleted_at IS NULL
`

type GetContractForRAGRow struct {
	ID           int64
	Title        sql.NullString
	Type         string
	Object       sql.NullString
	Content      string
	ClientName   string
	SupplierName string
	CreatedAt    sql.NullTime
}

func (q *Queries) GetContractForRAG(ctx context.Context, id int64) (GetContractForRAGRow, error) {
	row := q.db.QueryRowContext(ctx, getContractForRAG, id)
	var i GetContractForRAGRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Object,
		&i.Content,
		&i.ClientName,
		&i.SupplierName,
		&i.CreatedAt,
	)
	return i, err
}

const getContractForUpdate = `-- name: GetContractForUpdate :one
SELECT id, internal_id, contract_number, title, client_id, supplier_id,
       client_signer_id, supplier_signer_id, start_date, end_date,
       amount, type, status, description, object, fulfillment_place,
       dispute_resolution, has_confidentiality, guarantees, renewal_type,
       document_url, document_key, company_id, created_by, created_at, updated_at
FROM contracts
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetContractForUpdateParams struct {
	ID        int64
	CompanyID int64
}

type GetContractForUpdateRow struct {
	ID                 int64
	InternalID         string
	ContractNumber     string
	Title              sql.NullString
	ClientID           int64
	SupplierID         int64
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Type               string
	Status             string
	Description        sql.NullString
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	CompanyID          int64
	CreatedBy          sql.NullInt64
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

func (q *Queries) GetContractForUpdate(ctx context.Context, arg GetContractForUpdateParams) (GetContractForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getContractForUpdate, arg.ID, arg.CompanyID)
	var i GetContractForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractWithNames = `-- name: GetContractWithNames :one
SELECT
  c.id, c.internal_id, c.contract_number, c.title,
  c.client_id, c.supplier_id, c.client_signer_id, c.supplier_signer_id,
  c.start_date, c.end_date, c.amount, c.type, c.status,
  c.description, c.object, c.fulfillment_place, c.dispute_resolution,
  c.has_confidentiality, c.guarantees, c.renewal_type,
  c.document_url, c.document_key,
  c.company_id, c.created_by, c.created_at, c.updated_at,
  COALESCE(cl.name, '') AS client_name,
  COALESCE(s.name, '') AS supplier_name
FROM contracts c
LEFT JOIN clients cl ON cl.id = c.client_id AND cl.deleted_at IS NULL
LEFT JOIN suppliers s ON s.id = c.supplier_id AND s.deleted_at IS NULL
WHERE c.id = ? AND c.deleted_at IS NULL AND c.company_id = ?
LIMIT 1
`

type GetContractWithNamesParams struct {
	ID        int64
	CompanyID int64
}

type GetContractWithNamesRow struct {
	ID                 int64
	InternalID         string
	ContractNumber     string
	Title              sql.NullString
	ClientID           int64
	SupplierID         int64
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Type               string
	Status             string
	Description        sql.NullString
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	CompanyID          int64
	CreatedBy          sql.NullInt64
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	ClientName         string
	SupplierName       string
}

func (q *Queries) GetContractWithNames(ctx context.Context, arg GetContractWithNamesParams) (GetContractWithNamesRow, error) {
	row := q.db.QueryRowContext(ctx, getContractWithNames, arg.ID, arg.CompanyID)
	var i GetContractWithNamesRow
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.SupplierName,
	)
	return i, err
}

const getContractsByStatus = `-- name: GetContractsByStatus :many
SELECT id, internal_id, contract_number, title, end_date
FROM contracts
WHERE company_id = ? AND deleted_at IS NULL AND status = ?
ORDER BY end_date ASC
`

type GetContractsByStatusParams struct {
	CompanyID int64
	Status    string
}

type GetContractsByStatusRow struct {
	ID             int64
	InternalID     string
	ContractNumber string
	Title          sql.NullString
	EndDate        time.Time
}

func (q *Queries) GetContractsByStatus(ctx context.Context, arg GetContractsByStatusParams) ([]GetContractsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getContractsByStatus, arg.CompanyID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContractsByStatusRow
	for rows.Next() {
		var i GetContractsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractNumber,
			&i.Title,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiringSoonContracts = `-- name: GetExpiringSoonContracts :many
SELECT id, internal_id, contract_number, title, end_date, client_id, supplier_id
FROM contracts
WHERE company_id = ? AND deleted_at IS NULL
  AND date(end_date) BETWEEN date('now') AND date('now', '+30 days')
  AND status != 'expired'
ORDER BY end_date ASC
`

type GetExpiringSoonContractsRow struct {
	ID             int64
	InternalID     string
	ContractNumber string
	Title          sql.NullString
	EndDate        time.Time
	ClientID       int64
	SupplierID     int64
}

func (q *Queries) GetExpiringSoonContracts(ctx context.Context, companyID int64) ([]GetExpiringSoonContractsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiringSoonContracts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiringSoonContractsRow
	for rows.Next() {
		var i GetExpiringSoonContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractNumber,
			&i.Title,
			&i.EndDate,
			&i.ClientID,
			&i.SupplierID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxContractInternalID = `-- name: GetMaxContractInternalID :one
SELECT MAX(CAST(SUBSTR(internal_id, 10) AS INTEGER))
FROM contracts
WHERE internal_id LIKE 'CNT-' || ? || '-%' AND company_id = ?
`

type GetMaxContractInternalIDParams struct {
	Column1   sql.NullString
	CompanyID int64
}

func (q *Queries) GetMaxContractInternalID(ctx context.Context, arg GetMaxContractInternalIDParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxContractInternalID, arg.Column1, arg.CompanyID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getNewOrUpdatedContractIDs = `-- name: GetNewOrUpdatedContractIDs :many
SELECT id FROM contracts
WHERE deleted_at IS NULL
  AND (created_at > ? OR updated_at > ?)
ORDER BY id
`

type GetNewOrUpdatedContractIDsParams struct {
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetNewOrUpdatedContractIDs(ctx context.Context, arg GetNewOrUpdatedContractIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getNewOrUpdatedContractIDs, arg.CreatedAt, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentContracts = `-- name: GetRecentContracts :many
SELECT id, internal_id, contract_number, title, end_date, status
FROM contracts
WHERE company_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ?
`

type GetRecentContractsParams struct {
	CompanyID int64
	Limit     int64
}

type GetRecentContractsRow struct {
	ID             int64
	InternalID     string
	ContractNumber string
	Title          sql.NullString
	EndDate        time.Time
	Status         string
}

func (q *Queries) GetRecentContracts(ctx context.Context, arg GetRecentContractsParams) ([]GetRecentContractsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentContracts, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentContractsRow
	for rows.Next() {
		var i GetRecentContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractNumber,
			&i.Title,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierCompanyID = `-- name: GetSupplierCompanyID :one
SELECT company_id FROM suppliers
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSupplierCompanyID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getSupplierCompanyID, id)
	var company_id sql.NullInt64
	err := row.Scan(&company_id)
	return company_id, err
}

const listContractsByCompany = `-- name: ListContractsByCompany :many
SELECT id, internal_id, contract_number, title, client_id, supplier_id,
       start_date, end_date, amount, type, status, created_at
FROM contracts
WHERE company_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListContractsByCompanyRow struct {
	ID             int64
	InternalID     string
	ContractNumber string
	Title          sql.NullString
	ClientID       int64
	SupplierID     int64
	StartDate      time.Time
	EndDate        time.Time
	Amount         float64
	Type           string
	Status         string
	CreatedAt      sql.NullTime
}

func (q *Queries) ListContractsByCompany(ctx context.Context, companyID int64) ([]ListContractsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listContractsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsByCompanyRow
	for rows.Next() {
		var i ListContractsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractNumber,
			&i.Title,
			&i.ClientID,
			&i.SupplierID,
			&i.StartDate,
			&i.EndDate,
			&i.Amount,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsByCompanyWithNames = `-- name: ListContractsByCompanyWithNames :many
SELECT
  c.id, c.internal_id, c.contract_number, c.title,
  c.client_id, c.supplier_id,
  c.start_date, c.end_date, c.amount, c.type, c.status,
  COALESCE(cl.name, '') AS client_name,
  COALESCE(s.name, '') AS supplier_name
FROM contracts c
LEFT JOIN clients cl ON cl.id = c.client_id AND cl.deleted_at IS NULL
LEFT JOIN suppliers s ON s.id = c.supplier_id AND s.deleted_at IS NULL
WHERE c.deleted_at IS NULL AND c.company_id = ?
ORDER BY c.created_at DESC
`

type ListContractsByCompanyWithNamesRow struct {
	ID             int64
	InternalID     string
	ContractNumber string
	Title          sql.NullString
	ClientID       int64
	SupplierID     int64
	StartDate      time.Time
	EndDate        time.Time
	Amount         float64
	Type           string
	Status         string
	ClientName     string
	SupplierName   string
}

func (q *Queries) ListContractsByCompanyWithNames(ctx context.Context, companyID int64) ([]ListContractsByCompanyWithNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listContractsByCompanyWithNames, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsByCompanyWithNamesRow
	for rows.Next() {
		var i ListContractsByCompanyWithNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractNumber,
			&i.Title,
			&i.ClientID,
			&i.SupplierID,
			&i.StartDate,
			&i.EndDate,
			&i.Amount,
			&i.Type,
			&i.Status,
			&i.ClientName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringContracts = `-- name: ListExpiringContracts :many
SELECT
  c.id,
  c.contract_number,
  c.title,
  c.end_date,
  c.created_by,
  cl.name AS client_name,
  co.name AS company_name,
  cl.company_id
FROM contracts c
JOIN clients cl ON c.client_id = cl.id
JOIN companies co ON cl.company_id = co.id
WHERE c.end_date BETWEEN date('now', ? || ' days') AND date('now', ? || ' days')
  AND c.status = 'active'
  AND c.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM contract_expiry_notification_log l
      WHERE l.contract_id = c.id AND l.threshold_days = ?
  )
ORDER BY c.end_date ASC
LIMIT 1000
`

type ListExpiringContractsParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
}

type ListExpiringContractsRow struct {
	ID             int64
	ContractNumber string
	Title          sql.NullString
	EndDate        time.Time
	CreatedBy      sql.NullInt64
	ClientName     string
	CompanyName    string
	CompanyID      sql.NullInt64
}

func (q *Queries) ListExpiringContracts(ctx context.Context, arg ListExpiringContractsParams) ([]ListExpiringContractsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringContracts, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringContractsRow
	for rows.Next() {
		var i ListExpiringContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractNumber,
			&i.Title,
			&i.EndDate,
			&i.CreatedBy,
			&i.ClientName,
			&i.CompanyName,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContract = `-- name: UpdateContract :one
UPDATE contracts
SET
  title = ?,
  client_signer_id = ?, supplier_signer_id = ?,
  start_date = ?, end_date = ?, amount = ?,
  description = ?, object = ?, fulfillment_place = ?,
  dispute_resolution = ?, has_confidentiality = ?, guarantees = ?,
  renewal_type = ?, document_url = ?, document_key = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
RETURNING id, contract_number, title, client_id, supplier_id, client_signer_id, supplier_signer_id, start_date, end_date, amount, type, status, description, internal_id, company_id, object, fulfillment_place, dispute_resolution, has_confidentiality, guarantees, renewal_type, document_url, document_key, created_by, created_at, updated_at, deleted_at
`

type UpdateContractParams struct {
	Title              sql.NullString
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Description        sql.NullString
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	ID                 int64
	CompanyID          int64
}

func (q *Queries) UpdateContract(ctx context.Context, arg UpdateContractParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, updateContract,
		arg.Title,
		arg.ClientSignerID,
		arg.SupplierSignerID,
		arg.StartDate,
		arg.EndDate,
		arg.Amount,
		arg.Description,
		arg.Object,
		arg.FulfillmentPlace,
		arg.DisputeResolution,
		arg.HasConfidentiality,
		arg.Guarantees,
		arg.RenewalType,
		arg.DocumentUrl,
		arg.DocumentKey,
		arg.ID,
		arg.CompanyID,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.InternalID,
		&i.CompanyID,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateContractFields = `-- name: UpdateContractFields :one
UPDATE contracts
SET
  title = ?,
  client_signer_id = ?, supplier_signer_id = ?,
  start_date = ?, end_date = ?, amount = ?,
  description = ?, object = ?, fulfillment_place = ?,
  dispute_resolution = ?, has_confidentiality = ?, guarantees = ?,
  renewal_type = ?, document_url = COALESCE(?, document_url),
  document_key = COALESCE(?, document_key),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
RETURNING id, contract_number, title, client_id, supplier_id, client_signer_id, supplier_signer_id, start_date, end_date, amount, type, status, description, internal_id, company_id, object, fulfillment_place, dispute_resolution, has_confidentiality, guarantees, renewal_type, document_url, document_key, created_by, created_at, updated_at, deleted_at
`

type UpdateContractFieldsParams struct {
	Title              sql.NullString
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Description        sql.NullString
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	ID                 int64
	CompanyID          int64
}

func (q *Queries) UpdateContractFields(ctx context.Context, arg UpdateContractFieldsParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, updateContractFields,
		arg.Title,
		arg.ClientSignerID,
		arg.SupplierSignerID,
		arg.StartDate,
		arg.EndDate,
		arg.Amount,
		arg.Description,
		arg.Object,
		arg.FulfillmentPlace,
		arg.DisputeResolution,
		arg.HasConfidentiality,
		arg.Guarantees,
		arg.RenewalType,
		arg.DocumentUrl,
		arg.DocumentKey,
		arg.ID,
		arg.CompanyID,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ContractNumber,
		&i.Title,
		&i.ClientID,
		&i.SupplierID,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.StartDate,
		&i.EndDate,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.InternalID,
		&i.CompanyID,
		&i.Object,
		&i.FulfillmentPlace,
		&i.DisputeResolution,
		&i.HasConfidentiality,
		&i.Guarantees,
		&i.RenewalType,
		&i.DocumentUrl,
		&i.DocumentKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateContractStatus = `-- name: UpdateContractStatus :exec
UPDATE contracts
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type UpdateContractStatusParams struct {
	Status    string
	ID        int64
	CompanyID int64
}

func (q *Queries) UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateContractStatus, arg.Status, arg.ID, arg.CompanyID)
	return err
}
