// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_expiry_settings.sql

package db

import (
	"context"
)

const getContractExpirySettings = `-- name: GetContractExpirySettings :one
SELECT id, enabled, frequency_hours, thresholds_days, updated_by, updated_at
FROM contract_expiry_notification_settings
WHERE id = 1
`

func (q *Queries) GetContractExpirySettings(ctx context.Context) (ContractExpiryNotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, getContractExpirySettings)
	var i ContractExpiryNotificationSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.FrequencyHours,
		&i.ThresholdsDays,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
