// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"
	"database/sql"
)

const countDocumentsByEntity = `-- name: CountDocumentsByEntity :one
SELECT COUNT(*) FROM documents
WHERE entity_id = ? AND entity_type = ?
`

type CountDocumentsByEntityParams struct {
	EntityID   int64
	EntityType string
}

func (q *Queries) CountDocumentsByEntity(ctx context.Context, arg CountDocumentsByEntityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentsByEntity, arg.EntityID, arg.EntityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (
  entity_id, entity_type, filename, storage_path,
  mime_type, size_bytes, uploaded_by, company_id, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
)
RETURNING id, entity_id, entity_type, filename, storage_path, mime_type, size_bytes, company_id, uploaded_by, created_at
`

type CreateDocumentParams struct {
	EntityID    int64
	EntityType  string
	Filename    string
	StoragePath string
	MimeType    sql.NullString
	SizeBytes   sql.NullInt64
	UploadedBy  sql.NullInt64
	CompanyID   sql.NullInt64
}

// ============================================================
// documents queries
// Note: documents table does NOT have deleted_at (by design)
// ============================================================
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.EntityID,
		arg.EntityType,
		arg.Filename,
		arg.StoragePath,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedBy,
		arg.CompanyID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EntityType,
		&i.Filename,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CompanyID,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = ? AND company_id = ?
`

type DeleteDocumentParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, arg.ID, arg.CompanyID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, entity_id, entity_type, filename, storage_path,
       mime_type, size_bytes, uploaded_by, created_at
FROM documents
WHERE id = ? AND company_id = ?
LIMIT 1
`

type GetDocumentParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

type GetDocumentRow struct {
	ID          int64
	EntityID    int64
	EntityType  string
	Filename    string
	StoragePath string
	MimeType    sql.NullString
	SizeBytes   sql.NullInt64
	UploadedBy  sql.NullInt64
	CreatedAt   sql.NullTime
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.ID, arg.CompanyID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.EntityType,
		&i.Filename,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByEntity = `-- name: ListDocumentsByEntity :many
SELECT id, entity_id, entity_type, filename, storage_path,
       mime_type, size_bytes, uploaded_by, created_at
FROM documents
WHERE entity_id = ? AND entity_type = ? AND company_id = ?
ORDER BY created_at DESC
`

type ListDocumentsByEntityParams struct {
	EntityID   int64
	EntityType string
	CompanyID  sql.NullInt64
}

type ListDocumentsByEntityRow struct {
	ID          int64
	EntityID    int64
	EntityType  string
	Filename    string
	StoragePath string
	MimeType    sql.NullString
	SizeBytes   sql.NullInt64
	UploadedBy  sql.NullInt64
	CreatedAt   sql.NullTime
}

func (q *Queries) ListDocumentsByEntity(ctx context.Context, arg ListDocumentsByEntityParams) ([]ListDocumentsByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByEntity, arg.EntityID, arg.EntityType, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByEntityRow
	for rows.Next() {
		var i ListDocumentsByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.EntityType,
			&i.Filename,
			&i.StoragePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
