// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AiLegalChatHistory struct {
	ID               int64
	UserID           int64
	SessionID        string
	MessageType      string
	Content          string
	ContextDocuments sql.NullString
	Metadata         sql.NullString
	CreatedAt        sql.NullTime
}

type AiRateLimit struct {
	CompanyID int64
	Date      string
	Count     sql.NullInt64
}

type AppConfig struct {
	Key   string
	Value string
}

type AuditLog struct {
	ID            int64
	UserID        sql.NullInt64
	CompanyID     sql.NullInt64
	Action        string
	EntityType    string
	EntityID      sql.NullInt64
	PreviousState sql.NullString
	NewState      sql.NullString
	IpAddress     sql.NullString
	CreatedAt     sql.NullTime
	UserAgent     sql.NullString
	SessionID     sql.NullString
	ViolationFlag sql.NullBool
}

type AuthorizedSigner struct {
	ID          int64
	CompanyID   int64
	CompanyType string
	FirstName   string
	LastName    string
	Position    sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	CreatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Client struct {
	ID        int64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CompanyID sql.NullInt64
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Company struct {
	ID          int64
	Name        string
	Address     sql.NullString
	TaxID       sql.NullString
	CompanyType string
	ParentID    sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   sql.NullInt64
}

type Contract struct {
	ID                 int64
	ContractNumber     string
	Title              sql.NullString
	ClientID           int64
	SupplierID         int64
	ClientSignerID     sql.NullInt64
	SupplierSignerID   sql.NullInt64
	StartDate          time.Time
	EndDate            time.Time
	Amount             float64
	Type               string
	Status             string
	Description        sql.NullString
	InternalID         string
	CompanyID          int64
	Object             sql.NullString
	FulfillmentPlace   sql.NullString
	DisputeResolution  sql.NullString
	HasConfidentiality sql.NullInt64
	Guarantees         sql.NullString
	RenewalType        sql.NullString
	DocumentUrl        interface{}
	DocumentKey        interface{}
	CreatedBy          sql.NullInt64
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
}

type ContractExpiryNotificationLog struct {
	ID             int64
	ContractID     int64
	ThresholdDays  int64
	SentToUser     bool
	SentToAdmin    bool
	SentAt         sql.NullTime
	DeliveryStatus string
	ErrorMessage   sql.NullString
	Channel        string
	CreatedAt      time.Time
}

type ContractExpiryNotificationSetting struct {
	ID             int64
	Enabled        bool
	FrequencyHours int64
	ThresholdsDays string
	UpdatedBy      sql.NullInt64
	UpdatedAt      time.Time
}

type DbCapability struct {
	Capability string
	Supported  bool
	Notes      sql.NullString
}

type Document struct {
	ID          int64
	EntityID    int64
	EntityType  string
	Filename    string
	StoragePath string
	MimeType    sql.NullString
	SizeBytes   sql.NullInt64
	CompanyID   sql.NullInt64
	UploadedBy  sql.NullInt64
	CreatedAt   sql.NullTime
}

type LegalDocument struct {
	ID              int64
	Title           string
	DocumentType    string
	Source          sql.NullString
	SourceFilename  string
	Content         string
	ContentText     string
	ContentHash     string
	Language        sql.NullString
	Jurisdiction    sql.NullString
	EffectiveDate   sql.NullTime
	PublicationDate sql.NullTime
	GacetaNumber    sql.NullString
	ReferenceNumber sql.NullString
	Tags            sql.NullString
	ChunkCount      sql.NullInt64
	ChunkConfig     sql.NullString
	IsIndexed       sql.NullBool
	MimeType        sql.NullString
	SizeBytes       sql.NullInt64
	StoragePath     string
	CompanyID       int64
	UploadedBy      int64
	IndexedAt       sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type MiniragChunk struct {
	ID         int64
	ContractID int64
	ChunkIndex int64
	Content    string
	PageNumber sql.NullInt64
	ClauseType sql.NullString
	VectorID   int64
	CreatedAt  sql.NullTime
}

type Notification struct {
	ID         int64
	UserID     int64
	Type       string
	Title      string
	Message    sql.NullString
	EntityID   sql.NullInt64
	EntityType sql.NullString
	CompanyID  sql.NullInt64
	ReadAt     sql.NullTime
	CreatedAt  sql.NullTime
}

type NotificationSetting struct {
	ID         int64
	UserID     int64
	CompanyID  int64
	Enabled    sql.NullBool
	Thresholds sql.NullString
	Recipients sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type PasswordResetToken struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type PendingActivation struct {
	ID              int64
	UserID          int64
	CompanyID       sql.NullInt64
	CompanyName     sql.NullString
	CompanyAddress  sql.NullString
	CompanyTaxID    sql.NullString
	CompanyPhone    sql.NullString
	CompanyEmail    sql.NullString
	RoleAtCompany   sql.NullString
	FirstSupplierID sql.NullInt64
	FirstClientID   sql.NullInt64
	Status          sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type PendingApproval struct {
	ID            int64
	UserID        int64
	CompanyName   string
	CompanyID     sql.NullInt64
	Status        string
	RequestedRole string
	ReviewedBy    sql.NullInt64
	ReviewedAt    sql.NullTime
	Notes         sql.NullString
	CreatedAt     sql.NullTime
}

type RegistrationCode struct {
	ID        int64
	UserID    int64
	CodeHash  string
	ExpiresAt time.Time
	Attempts  sql.NullInt64
	CreatedAt sql.NullTime
}

type Session struct {
	Token        string
	UserID       int64
	CompanyID    int64
	ExpiresAt    time.Time
	CreatedAt    sql.NullTime
	LastActivity sql.NullTime
}

type Supplement struct {
	ID               int64
	ContractID       int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Modifications    sql.NullString
	Status           string
	ClientSignerID   sql.NullInt64
	SupplierSignerID sql.NullInt64
	InternalID       sql.NullString
	CompanyID        sql.NullInt64
	ModificationType sql.NullString
	DeletedAt        sql.NullTime
	CreatedBy        sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Supplier struct {
	ID        int64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CompanyID sql.NullInt64
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type SystemSetting struct {
	ID        int64
	Key       string
	Value     sql.NullString
	Category  string
	UpdatedBy sql.NullInt64
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type TenantContextSession struct {
	ID           int64
	SessionToken string
	UserID       int64
	CompanyID    int64
	IpAddress    sql.NullString
	UserAgent    sql.NullString
	CreatedAt    sql.NullTime
	LastSeen     sql.NullTime
}

type TenantIsolationPolicy struct {
	ID           int64
	TableName    string
	TenantColumn string
	PolicyType   string
	Enabled      sql.NullBool
	Notes        sql.NullString
}

type User struct {
	ID                  int64
	Name                string
	Email               string
	PasswordHash        string
	Role                string
	Status              string
	CompanyID           sql.NullInt64
	LastAccess          sql.NullTime
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	SetupCompleted      sql.NullBool
	RoleAtCompany       sql.NullString
	DigitalSignatureUrl sql.NullString
	DigitalSignatureKey sql.NullString
	PublicCertUrl       sql.NullString
	PublicCertKey       sql.NullString
	AvatarUrl           sql.NullString
	AvatarKey           sql.NullString
}

type UserCompany struct {
	UserID    int64
	CompanyID int64
	IsDefault int64
}

type VPotentialCrossTenantAccess struct {
	ID          int64
	UserID      sql.NullInt64
	CompanyID   sql.NullInt64
	Action      string
	TableName   string
	CreatedAt   sql.NullTime
	UserEmail   string
	CompanyName string
}
