// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = ? AND company_id = ? AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	UserID    int64
	CompanyID sql.NullInt64
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, arg.UserID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, type, title, message, entity_id, entity_type, company_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, user_id, type, title, message, entity_id, entity_type, company_id, read_at, created_at
`

type CreateNotificationParams struct {
	UserID     int64
	Type       string
	Title      string
	Message    sql.NullString
	EntityID   sql.NullInt64
	EntityType sql.NullString
	CompanyID  sql.NullInt64
}

// ============================================================
// notifications queries
// ============================================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.EntityID,
		arg.EntityType,
		arg.CompanyID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.EntityID,
		&i.EntityType,
		&i.CompanyID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = ? AND user_id = ? AND company_id = ?
`

type DeleteNotificationParams struct {
	ID        int64
	UserID    int64
	CompanyID sql.NullInt64
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, arg.ID, arg.UserID, arg.CompanyID)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, title, message, entity_id, entity_type, read_at, created_at
FROM notifications
WHERE id = ? AND user_id = ? AND company_id = ?
LIMIT 1
`

type GetNotificationParams struct {
	ID        int64
	UserID    int64
	CompanyID sql.NullInt64
}

type GetNotificationRow struct {
	ID         int64
	UserID     int64
	Type       string
	Title      string
	Message    sql.NullString
	EntityID   sql.NullInt64
	EntityType sql.NullString
	ReadAt     sql.NullTime
	CreatedAt  sql.NullTime
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (GetNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, getNotification, arg.ID, arg.UserID, arg.CompanyID)
	var i GetNotificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.EntityID,
		&i.EntityType,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllNotificationsByUser = `-- name: ListAllNotificationsByUser :many
SELECT id, user_id, type, title, message, entity_id, entity_type, read_at, created_at
FROM notifications
WHERE user_id = ? AND company_id = ?
ORDER BY created_at DESC
LIMIT 100
`

type ListAllNotificationsByUserParams struct {
	UserID    int64
	CompanyID sql.NullInt64
}

type ListAllNotificationsByUserRow struct {
	ID         int64
	UserID     int64
	Type       string
	Title      string
	Message    sql.NullString
	EntityID   sql.NullInt64
	EntityType sql.NullString
	ReadAt     sql.NullTime
	CreatedAt  sql.NullTime
}

func (q *Queries) ListAllNotificationsByUser(ctx context.Context, arg ListAllNotificationsByUserParams) ([]ListAllNotificationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllNotificationsByUser, arg.UserID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllNotificationsByUserRow
	for rows.Next() {
		var i ListAllNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.EntityID,
			&i.EntityType,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, message, entity_id, entity_type, read_at, created_at
FROM notifications
WHERE user_id = ? AND company_id = ? AND read_at IS NULL
ORDER BY created_at DESC
`

type ListNotificationsByUserParams struct {
	UserID    int64
	CompanyID sql.NullInt64
}

type ListNotificationsByUserRow struct {
	ID         int64
	UserID     int64
	Type       string
	Title      string
	Message    sql.NullString
	EntityID   sql.NullInt64
	EntityType sql.NullString
	ReadAt     sql.NullTime
	CreatedAt  sql.NullTime
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]ListNotificationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUser, arg.UserID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsByUserRow
	for rows.Next() {
		var i ListNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.EntityID,
			&i.EntityType,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND company_id = ? AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	UserID    int64
	CompanyID sql.NullInt64
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, arg.UserID, arg.CompanyID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND company_id = ?
`

type MarkNotificationReadParams struct {
	ID        int64
	UserID    int64
	CompanyID sql.NullInt64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID, arg.CompanyID)
	return err
}
