// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_settings.sql

package db

import (
	"context"
	"database/sql"
)

const getNotificationSettings = `-- name: GetNotificationSettings :one

SELECT id, user_id, company_id, enabled, thresholds, recipients, created_at, updated_at
FROM notification_settings
WHERE user_id = ? AND company_id = ?
LIMIT 1
`

type GetNotificationSettingsParams struct {
	UserID    int64
	CompanyID int64
}

// ============================================================
// notification_settings queries
// ============================================================
func (q *Queries) GetNotificationSettings(ctx context.Context, arg GetNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSettings, arg.UserID, arg.CompanyID)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Enabled,
		&i.Thresholds,
		&i.Recipients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :exec
INSERT INTO notification_settings (user_id, company_id, enabled, thresholds, recipients, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, company_id) DO UPDATE SET
  enabled = excluded.enabled,
  thresholds = excluded.thresholds,
  recipients = excluded.recipients,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertNotificationSettingsParams struct {
	UserID     int64
	CompanyID  int64
	Enabled    sql.NullBool
	Thresholds sql.NullString
	Recipients sql.NullString
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationSettings,
		arg.UserID,
		arg.CompanyID,
		arg.Enabled,
		arg.Thresholds,
		arg.Recipients,
	)
	return err
}
