// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec

INSERT INTO password_reset_tokens (user_id, token, expires_at, created_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
`

type CreatePasswordResetTokenParams struct {
	UserID    int64
	Token     string
	ExpiresAt time.Time
}

// ============================================================
// password_reset_tokens queries
// ============================================================
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteUsedPasswordResetTokens = `-- name: DeleteUsedPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE used_at IS NOT NULL
`

func (q *Queries) DeleteUsedPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsedPasswordResetTokens)
	return err
}

const getLatestPasswordResetTokenForUser = `-- name: GetLatestPasswordResetTokenForUser :one
SELECT id, token, expires_at, used_at
FROM password_reset_tokens
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestPasswordResetTokenForUserRow struct {
	ID        int64
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

func (q *Queries) GetLatestPasswordResetTokenForUser(ctx context.Context, userID int64) (GetLatestPasswordResetTokenForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestPasswordResetTokenForUser, userID)
	var i GetLatestPasswordResetTokenForUserRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token = ?
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT id, user_id, token, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token = ? AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getValidPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE token = ?
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, token)
	return err
}
