// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_approvals.sql

package db

import (
	"context"
	"database/sql"
)

const approvePendingApproval = `-- name: ApprovePendingApproval :exec
UPDATE pending_approvals
SET status = 'approved', reviewed_by = ?, reviewed_at = ?, company_id = ?, notes = ?
WHERE id = ?
`

type ApprovePendingApprovalParams struct {
	ReviewedBy sql.NullInt64
	ReviewedAt sql.NullTime
	CompanyID  sql.NullInt64
	Notes      sql.NullString
	ID         int64
}

func (q *Queries) ApprovePendingApproval(ctx context.Context, arg ApprovePendingApprovalParams) error {
	_, err := q.db.ExecContext(ctx, approvePendingApproval,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.CompanyID,
		arg.Notes,
		arg.ID,
	)
	return err
}

const getPendingApproval = `-- name: GetPendingApproval :one
SELECT id, user_id, company_name, company_id, requested_role, status
FROM pending_approvals
WHERE id = ? AND status = 'pending'
LIMIT 1
`

type GetPendingApprovalRow struct {
	ID            int64
	UserID        int64
	CompanyName   string
	CompanyID     sql.NullInt64
	RequestedRole string
	Status        string
}

func (q *Queries) GetPendingApproval(ctx context.Context, id int64) (GetPendingApprovalRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingApproval, id)
	var i GetPendingApprovalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyID,
		&i.RequestedRole,
		&i.Status,
	)
	return i, err
}

const getPendingApprovalUser = `-- name: GetPendingApprovalUser :one
SELECT user_id, company_name FROM pending_approvals
WHERE id = ? AND status = 'pending'
LIMIT 1
`

type GetPendingApprovalUserRow struct {
	UserID      int64
	CompanyName string
}

func (q *Queries) GetPendingApprovalUser(ctx context.Context, id int64) (GetPendingApprovalUserRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingApprovalUser, id)
	var i GetPendingApprovalUserRow
	err := row.Scan(&i.UserID, &i.CompanyName)
	return i, err
}

const listPendingApprovals = `-- name: ListPendingApprovals :many

SELECT pa.id, pa.user_id, u.name, u.email, pa.company_name, pa.company_id, pa.requested_role, pa.status, pa.created_at
FROM pending_approvals pa
JOIN users u ON u.id = pa.user_id
WHERE pa.status = 'pending' AND u.deleted_at IS NULL
ORDER BY pa.created_at DESC
`

type ListPendingApprovalsRow struct {
	ID            int64
	UserID        int64
	Name          string
	Email         string
	CompanyName   string
	CompanyID     sql.NullInt64
	RequestedRole string
	Status        string
	CreatedAt     sql.NullTime
}

// ============================================================
// pending_approvals queries
// ============================================================
func (q *Queries) ListPendingApprovals(ctx context.Context) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalsRow
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CompanyName,
			&i.CompanyID,
			&i.RequestedRole,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPendingApproval = `-- name: RejectPendingApproval :exec
UPDATE pending_approvals
SET status = 'rejected', reviewed_by = ?, reviewed_at = ?, notes = ?
WHERE id = ?
`

type RejectPendingApprovalParams struct {
	ReviewedBy sql.NullInt64
	ReviewedAt sql.NullTime
	Notes      sql.NullString
	ID         int64
}

func (q *Queries) RejectPendingApproval(ctx context.Context, arg RejectPendingApprovalParams) error {
	_, err := q.db.ExecContext(ctx, rejectPendingApproval,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.Notes,
		arg.ID,
	)
	return err
}
