// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_activations.sql

package db

import (
	"context"
	"database/sql"
)

const createPendingActivation = `-- name: CreatePendingActivation :exec
INSERT INTO pending_activations (user_id, company_id, company_name, role_at_company, status)
VALUES (?, ?, ?, ?, 'pending_activation')
`

type CreatePendingActivationParams struct {
	UserID        int64
	CompanyID     sql.NullInt64
	CompanyName   sql.NullString
	RoleAtCompany sql.NullString
}

func (q *Queries) CreatePendingActivation(ctx context.Context, arg CreatePendingActivationParams) error {
	_, err := q.db.ExecContext(ctx, createPendingActivation,
		arg.UserID,
		arg.CompanyID,
		arg.CompanyName,
		arg.RoleAtCompany,
	)
	return err
}

const listPendingActivations = `-- name: ListPendingActivations :many

SELECT pa.id, pa.user_id, u.name, u.email, pa.company_name, pa.company_id, pa.role_at_company, pa.status, pa.created_at
FROM pending_activations pa
JOIN users u ON u.id = pa.user_id
WHERE pa.status = 'pending_activation' AND u.deleted_at IS NULL
ORDER BY pa.created_at DESC
`

type ListPendingActivationsRow struct {
	ID            int64
	UserID        int64
	Name          string
	Email         string
	CompanyName   sql.NullString
	CompanyID     sql.NullInt64
	RoleAtCompany sql.NullString
	Status        sql.NullString
	CreatedAt     sql.NullTime
}

// ============================================================
// pending_activations queries
// ============================================================
func (q *Queries) ListPendingActivations(ctx context.Context) ([]ListPendingActivationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingActivations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingActivationsRow
	for rows.Next() {
		var i ListPendingActivationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CompanyName,
			&i.CompanyID,
			&i.RoleAtCompany,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
