// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ApprovePendingApproval(ctx context.Context, arg ApprovePendingApprovalParams) error
	CheckUserCompanyAccess(ctx context.Context, arg CheckUserCompanyAccessParams) (int64, error)
	CleanupOldRateLimits(ctx context.Context) error
	ClientExists(ctx context.Context, arg ClientExistsParams) (int64, error)
	ContractExists(ctx context.Context, arg ContractExistsParams) (int64, error)
	CountActiveContracts(ctx context.Context, companyID int64) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountClientsByCompany(ctx context.Context, companyID sql.NullInt64) (int64, error)
	CountCompanies(ctx context.Context) (int64, error)
	CountContractsByCompany(ctx context.Context, companyID int64) (int64, error)
	CountDocumentsByEntity(ctx context.Context, arg CountDocumentsByEntityParams) (int64, error)
	CountLegalDocuments(ctx context.Context) (int64, error)
	CountSupplementsByContract(ctx context.Context, contractID int64) (int64, error)
	CountSuppliersByCompany(ctx context.Context, companyID sql.NullInt64) (int64, error)
	CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error)
	CountUserCompanyAccess(ctx context.Context, arg CountUserCompanyAccessParams) (int64, error)
	// ============================================================
	// audit_logs queries
	// Note: audit_logs table does NOT have deleted_at (audit trail)
	// ============================================================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateCompanySimple(ctx context.Context, arg CreateCompanySimpleParams) (Company, error)
	CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error)
	// ============================================================
	// documents queries
	// Note: documents table does NOT have deleted_at (by design)
	// ============================================================
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	// ========== ai_legal_chat_history ==========
	// Note: ai_legal_chat_history does NOT have deleted_at (chat history)
	CreateLegalChatMessage(ctx context.Context, arg CreateLegalChatMessageParams) (AiLegalChatHistory, error)
	// ============================================================
	// ai_legal queries (legal_documents + ai_legal_chat_history)
	// ============================================================
	// ========== legal_documents ==========
	CreateLegalDocument(ctx context.Context, arg CreateLegalDocumentParams) (LegalDocument, error)
	// ============================================================
	// notifications queries
	// ============================================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ============================================================
	// password_reset_tokens queries
	// ============================================================
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePendingActivation(ctx context.Context, arg CreatePendingActivationParams) error
	// ============================================================
	// registration_codes queries
	// ============================================================
	CreateRegistrationCode(ctx context.Context, arg CreateRegistrationCodeParams) error
	// ============================================================
	// sessions queries
	// ============================================================
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSigner(ctx context.Context, arg CreateSignerParams) (AuthorizedSigner, error)
	CreateSupplement(ctx context.Context, arg CreateSupplementParams) (Supplement, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateUserCompany(ctx context.Context, arg CreateUserCompanyParams) error
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteCompany(ctx context.Context, id int64) error
	DeleteContract(ctx context.Context, arg DeleteContractParams) error
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error
	DeleteExpiredPasswordResetTokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteLegalChatSession(ctx context.Context, sessionID string) error
	DeleteLegalDocument(ctx context.Context, id int64) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOldRegistrationCodes(ctx context.Context) error
	DeleteRegistrationCode(ctx context.Context, id int64) error
	DeleteSessionByUserID(ctx context.Context, userID int64) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteSigner(ctx context.Context, id int64) error
	DeleteSupplement(ctx context.Context, arg DeleteSupplementParams) error
	DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) error
	DeleteUsedPasswordResetTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id int64) error
	GetActiveContracts(ctx context.Context, companyID int64) ([]GetActiveContractsRow, error)
	GetActiveSessionByToken(ctx context.Context, token string) (Session, error)
	GetActiveSupplements(ctx context.Context, contractID int64) ([]GetActiveSupplementsRow, error)
	GetAllContractIDsForRAG(ctx context.Context) ([]int64, error)
	GetAllSettings(ctx context.Context) ([]GetAllSettingsRow, error)
	GetAvatarFields(ctx context.Context, id int64) (GetAvatarFieldsRow, error)
	GetBasicUserByEmail(ctx context.Context, email string) (GetBasicUserByEmailRow, error)
	GetBoolSetting(ctx context.Context, key string) (sql.NullString, error)
	// ============================================================
	// clients queries
	// ============================================================
	GetClientByID(ctx context.Context, id int64) (GetClientByIDRow, error)
	GetClientByIDWithCompany(ctx context.Context, arg GetClientByIDWithCompanyParams) (GetClientByIDWithCompanyRow, error)
	GetClientCompanyID(ctx context.Context, id int64) (sql.NullInt64, error)
	GetClientName(ctx context.Context, arg GetClientNameParams) (string, error)
	GetCompanyByID(ctx context.Context, id int64) (GetCompanyByIDRow, error)
	GetCompanyType(ctx context.Context, id int64) (string, error)
	GetCompanyTypeByID(ctx context.Context, id int64) (string, error)
	GetCompanyWithParent(ctx context.Context, id int64) (GetCompanyWithParentRow, error)
	// ============================================================
	// contracts queries
	// ============================================================
	GetContractByID(ctx context.Context, arg GetContractByIDParams) (GetContractByIDRow, error)
	GetContractByInternalID(ctx context.Context, arg GetContractByInternalIDParams) (Contract, error)
	GetContractExpirySettings(ctx context.Context) (ContractExpiryNotificationSetting, error)
	GetContractForRAG(ctx context.Context, id int64) (GetContractForRAGRow, error)
	GetContractForUpdate(ctx context.Context, arg GetContractForUpdateParams) (GetContractForUpdateRow, error)
	GetContractWithNames(ctx context.Context, arg GetContractWithNamesParams) (GetContractWithNamesRow, error)
	GetContractsByStatus(ctx context.Context, arg GetContractsByStatusParams) ([]GetContractsByStatusRow, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error)
	GetExpiringSoonContracts(ctx context.Context, companyID int64) ([]GetExpiringSoonContractsRow, error)
	GetLastLegalDocumentIndexTime(ctx context.Context) (interface{}, error)
	GetLatestPasswordResetTokenForUser(ctx context.Context, userID int64) (GetLatestPasswordResetTokenForUserRow, error)
	GetLatestRegistrationCodeForUser(ctx context.Context, userID int64) (GetLatestRegistrationCodeForUserRow, error)
	GetLatestSupplementNumber(ctx context.Context, contractID int64) (int64, error)
	GetLegalChatHistoryBySession(ctx context.Context, sessionID string) ([]AiLegalChatHistory, error)
	GetLegalChatMessagesBySession(ctx context.Context, sessionID string) ([]AiLegalChatHistory, error)
	GetLegalChatSessionsByUser(ctx context.Context, userID int64) ([]GetLegalChatSessionsByUserRow, error)
	GetLegalDocument(ctx context.Context, id int64) (LegalDocument, error)
	GetMaxContractInternalID(ctx context.Context, arg GetMaxContractInternalIDParams) (interface{}, error)
	GetMaxSupplementInternalID(ctx context.Context, arg GetMaxSupplementInternalIDParams) (interface{}, error)
	GetNewOrUpdatedContractIDs(ctx context.Context, arg GetNewOrUpdatedContractIDsParams) ([]int64, error)
	GetNotification(ctx context.Context, arg GetNotificationParams) (GetNotificationRow, error)
	// ============================================================
	// notification_settings queries
	// ============================================================
	GetNotificationSettings(ctx context.Context, arg GetNotificationSettingsParams) (NotificationSetting, error)
	GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetPendingApproval(ctx context.Context, id int64) (GetPendingApprovalRow, error)
	GetPendingApprovalUser(ctx context.Context, id int64) (GetPendingApprovalUserRow, error)
	GetRateLimitInfo(ctx context.Context, arg GetRateLimitInfoParams) ([]GetRateLimitInfoRow, error)
	GetRecentContracts(ctx context.Context, arg GetRecentContractsParams) ([]GetRecentContractsRow, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetSessionForRefresh(ctx context.Context, token string) (GetSessionForRefreshRow, error)
	// ============================================================
	// system_settings queries
	// ============================================================
	// Soft-delete pattern: All SELECTs include "AND deleted_at IS NULL"
	// unless explicitly fetching all (including deleted).
	// ============================================================
	GetSettingValue(ctx context.Context, key string) (sql.NullString, error)
	GetSettingsByKeys(ctx context.Context, arg GetSettingsByKeysParams) ([]GetSettingsByKeysRow, error)
	// ============================================================
	// authorized_signers queries
	// ============================================================
	GetSignerByID(ctx context.Context, id int64) (GetSignerByIDRow, error)
	GetSignerByIDWithCompany(ctx context.Context, arg GetSignerByIDWithCompanyParams) (GetSignerByIDWithCompanyRow, error)
	GetSignerCompanyOwnership(ctx context.Context, id int64) (int64, error)
	GetSignerForAudit(ctx context.Context, id int64) (GetSignerForAuditRow, error)
	GetSignerForContractValidation(ctx context.Context, arg GetSignerForContractValidationParams) (GetSignerForContractValidationRow, error)
	GetSignerWithValidation(ctx context.Context, arg GetSignerWithValidationParams) (GetSignerWithValidationRow, error)
	GetSubsidiaries(ctx context.Context, parentID sql.NullInt64) ([]GetSubsidiariesRow, error)
	// ============================================================
	// supplements queries
	// ============================================================
	GetSupplementByID(ctx context.Context, arg GetSupplementByIDParams) (GetSupplementByIDRow, error)
	GetSupplementStatus(ctx context.Context, arg GetSupplementStatusParams) (string, error)
	// ============================================================
	// suppliers queries
	// ============================================================
	GetSupplierByID(ctx context.Context, arg GetSupplierByIDParams) (GetSupplierByIDRow, error)
	GetSupplierByIDWithCompany(ctx context.Context, arg GetSupplierByIDWithCompanyParams) (GetSupplierByIDWithCompanyRow, error)
	GetSupplierCompanyID(ctx context.Context, id int64) (sql.NullInt64, error)
	GetSupplierName(ctx context.Context, arg GetSupplierNameParams) (string, error)
	GetTodayRateLimitCount(ctx context.Context, companyID int64) (interface{}, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	// ============================================================
	// users queries
	// ============================================================
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserCompanyID(ctx context.Context, id int64) (sql.NullInt64, error)
	GetUserCompanyIDUnscoped(ctx context.Context, id int64) (sql.NullInt64, error)
	// ============================================================
	// user_companies queries
	// ============================================================
	GetUserDefaultCompany(ctx context.Context, userID int64) (int64, error)
	GetUserForSignIn(ctx context.Context, email string) (GetUserForSignInRow, error)
	GetUserRole(ctx context.Context, id int64) (string, error)
	GetUsersByCompany(ctx context.Context, companyID sql.NullInt64) ([]GetUsersByCompanyRow, error)
	GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetValidRegistrationCode(ctx context.Context, arg GetValidRegistrationCodeParams) (GetValidRegistrationCodeRow, error)
	// ============================================================
	// ai_rate_limits queries
	// Note: This table does NOT have deleted_at (metrics/audit data)
	// ============================================================
	IncrementRateLimit(ctx context.Context, arg IncrementRateLimitParams) (sql.NullInt64, error)
	IncrementRateLimitCount(ctx context.Context, companyID int64) error
	IncrementRegistrationAttempts(ctx context.Context, userID int64) error
	ListActiveAdminEmails(ctx context.Context) ([]string, error)
	// ============================================================
	// companies queries
	// ============================================================
	ListAllCompanies(ctx context.Context) ([]ListAllCompaniesRow, error)
	ListAllCompaniesOrdered(ctx context.Context) ([]ListAllCompaniesOrderedRow, error)
	ListAllNotificationsByUser(ctx context.Context, arg ListAllNotificationsByUserParams) ([]ListAllNotificationsByUserRow, error)
	ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error)
	ListAuditLogsByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListAuditLogsByCompanyRow, error)
	ListAuditLogsByFilters(ctx context.Context, arg ListAuditLogsByFiltersParams) ([]ListAuditLogsByFiltersRow, error)
	ListClientsByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListClientsByCompanyRow, error)
	ListCompanies(ctx context.Context) ([]ListCompaniesRow, error)
	ListCompaniesForUser(ctx context.Context, userID int64) ([]ListCompaniesForUserRow, error)
	ListContractsByCompany(ctx context.Context, companyID int64) ([]ListContractsByCompanyRow, error)
	ListContractsByCompanyWithNames(ctx context.Context, companyID int64) ([]ListContractsByCompanyWithNamesRow, error)
	ListDocumentsByEntity(ctx context.Context, arg ListDocumentsByEntityParams) ([]ListDocumentsByEntityRow, error)
	ListExpiringContracts(ctx context.Context, arg ListExpiringContractsParams) ([]ListExpiringContractsRow, error)
	ListLegalDocuments(ctx context.Context, arg ListLegalDocumentsParams) ([]LegalDocument, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]ListNotificationsByUserRow, error)
	// ============================================================
	// pending_activations queries
	// ============================================================
	ListPendingActivations(ctx context.Context) ([]ListPendingActivationsRow, error)
	// ============================================================
	// pending_approvals queries
	// ============================================================
	ListPendingApprovals(ctx context.Context) ([]ListPendingApprovalsRow, error)
	ListSignersByClient(ctx context.Context, companyID int64) ([]ListSignersByClientRow, error)
	ListSignersByCompany(ctx context.Context, companyID int64) ([]ListSignersByCompanyRow, error)
	ListSignersByCompanyAndType(ctx context.Context, arg ListSignersByCompanyAndTypeParams) ([]ListSignersByCompanyAndTypeRow, error)
	ListSignersBySupplier(ctx context.Context, companyID int64) ([]ListSignersBySupplierRow, error)
	ListSupplementsByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListSupplementsByCompanyRow, error)
	ListSupplementsByContract(ctx context.Context, contractID int64) ([]ListSupplementsByContractRow, error)
	ListSuppliersByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListSuppliersByCompanyRow, error)
	ListUserCompanies(ctx context.Context, userID int64) ([]ListUserCompaniesRow, error)
	MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkPasswordResetTokenUsed(ctx context.Context, token string) error
	RejectPendingApproval(ctx context.Context, arg RejectPendingApprovalParams) error
	ResetUserDefaultCompanies(ctx context.Context, userID int64) error
	SessionExists(ctx context.Context, token string) (int64, error)
	SetDefaultCompany(ctx context.Context, arg SetDefaultCompanyParams) error
	SetSettingValue(ctx context.Context, arg SetSettingValueParams) error
	SignerExists(ctx context.Context, arg SignerExistsParams) (int64, error)
	SupplementExists(ctx context.Context, arg SupplementExistsParams) (int64, error)
	SupplierExists(ctx context.Context, arg SupplierExistsParams) (int64, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateContract(ctx context.Context, arg UpdateContractParams) (Contract, error)
	UpdateContractFields(ctx context.Context, arg UpdateContractFieldsParams) (Contract, error)
	UpdateContractStatus(ctx context.Context, arg UpdateContractStatusParams) error
	UpdateLegalDocumentIndexed(ctx context.Context, arg UpdateLegalDocumentIndexedParams) error
	UpdateSessionActivityAndExpiry(ctx context.Context, arg UpdateSessionActivityAndExpiryParams) error
	UpdateSessionCompany(ctx context.Context, arg UpdateSessionCompanyParams) error
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error
	UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) error
	UpdateSigner(ctx context.Context, arg UpdateSignerParams) (AuthorizedSigner, error)
	UpdateSupplement(ctx context.Context, arg UpdateSupplementParams) error
	UpdateSupplementStatus(ctx context.Context, arg UpdateSupplementStatusParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserCompany(ctx context.Context, arg UpdateUserCompanyParams) error
	UpdateUserLastAccess(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserURLFields(ctx context.Context, arg UpdateUserURLFieldsParams) error
	UpsertNotificationLog(ctx context.Context, arg UpsertNotificationLogParams) error
	UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) error
	UserCompanyExists(ctx context.Context, arg UserCompanyExistsParams) (int64, error)
	UserExists(ctx context.Context, email string) (int64, error)
}

var _ Querier = (*Queries)(nil)
