// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_codes.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRegistrationCode = `-- name: CreateRegistrationCode :exec

INSERT INTO registration_codes (user_id, code_hash, expires_at, created_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateRegistrationCodeParams struct {
	UserID    int64
	CodeHash  string
	ExpiresAt time.Time
}

// ============================================================
// registration_codes queries
// ============================================================
func (q *Queries) CreateRegistrationCode(ctx context.Context, arg CreateRegistrationCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const deleteOldRegistrationCodes = `-- name: DeleteOldRegistrationCodes :exec
DELETE FROM registration_codes
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteOldRegistrationCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldRegistrationCodes)
	return err
}

const deleteRegistrationCode = `-- name: DeleteRegistrationCode :exec
DELETE FROM registration_codes
WHERE id = ?
`

func (q *Queries) DeleteRegistrationCode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRegistrationCode, id)
	return err
}

const getLatestRegistrationCodeForUser = `-- name: GetLatestRegistrationCodeForUser :one
SELECT id, code_hash, expires_at, attempts
FROM registration_codes
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestRegistrationCodeForUserRow struct {
	ID        int64
	CodeHash  string
	ExpiresAt time.Time
	Attempts  sql.NullInt64
}

func (q *Queries) GetLatestRegistrationCodeForUser(ctx context.Context, userID int64) (GetLatestRegistrationCodeForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestRegistrationCodeForUser, userID)
	var i GetLatestRegistrationCodeForUserRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const getValidRegistrationCode = `-- name: GetValidRegistrationCode :one
SELECT id, code_hash, user_id
FROM registration_codes
WHERE user_id = ? AND code_hash = ?
  AND expires_at > CURRENT_TIMESTAMP AND attempts < 3
`

type GetValidRegistrationCodeParams struct {
	UserID   int64
	CodeHash string
}

type GetValidRegistrationCodeRow struct {
	ID       int64
	CodeHash string
	UserID   int64
}

func (q *Queries) GetValidRegistrationCode(ctx context.Context, arg GetValidRegistrationCodeParams) (GetValidRegistrationCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getValidRegistrationCode, arg.UserID, arg.CodeHash)
	var i GetValidRegistrationCodeRow
	err := row.Scan(&i.ID, &i.CodeHash, &i.UserID)
	return i, err
}

const incrementRegistrationAttempts = `-- name: IncrementRegistrationAttempts :exec
UPDATE registration_codes
SET attempts = attempts + 1
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) IncrementRegistrationAttempts(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, incrementRegistrationAttempts, userID)
	return err
}
