// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token, user_id, company_id, expires_at, created_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING token, user_id, company_id, expires_at, created_at, last_activity
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	CompanyID int64
	ExpiresAt time.Time
}

// ============================================================
// sessions queries
// ============================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.CompanyID,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CompanyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActivity,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByUserID = `-- name: DeleteSessionByUserID :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByUserID, userID)
	return err
}

const getActiveSessionByToken = `-- name: GetActiveSessionByToken :one
SELECT token, user_id, company_id, expires_at, created_at, last_activity FROM sessions
WHERE token = ? AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetActiveSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CompanyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActivity,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT token, user_id, company_id, expires_at, created_at
FROM sessions
WHERE token = ?
LIMIT 1
`

type GetSessionByTokenRow struct {
	Token     string
	UserID    int64
	CompanyID int64
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CompanyID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionForRefresh = `-- name: GetSessionForRefresh :one
SELECT last_activity, expires_at
FROM sessions
WHERE token = ? AND expires_at > datetime('now')
LIMIT 1
`

type GetSessionForRefreshRow struct {
	LastActivity sql.NullTime
	ExpiresAt    time.Time
}

func (q *Queries) GetSessionForRefresh(ctx context.Context, token string) (GetSessionForRefreshRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionForRefresh, token)
	var i GetSessionForRefreshRow
	err := row.Scan(&i.LastActivity, &i.ExpiresAt)
	return i, err
}

const sessionExists = `-- name: SessionExists :one
SELECT COUNT(*) FROM sessions
WHERE token = ?
`

func (q *Queries) SessionExists(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sessionExists, token)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSessionActivityAndExpiry = `-- name: UpdateSessionActivityAndExpiry :exec
UPDATE sessions
SET last_activity = CURRENT_TIMESTAMP, expires_at = ?
WHERE token = ?
`

type UpdateSessionActivityAndExpiryParams struct {
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) UpdateSessionActivityAndExpiry(ctx context.Context, arg UpdateSessionActivityAndExpiryParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivityAndExpiry, arg.ExpiresAt, arg.Token)
	return err
}

const updateSessionCompany = `-- name: UpdateSessionCompany :exec
UPDATE sessions
SET company_id = ?
WHERE token = ?
`

type UpdateSessionCompanyParams struct {
	CompanyID int64
	Token     string
}

func (q *Queries) UpdateSessionCompany(ctx context.Context, arg UpdateSessionCompanyParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionCompany, arg.CompanyID, arg.Token)
	return err
}

const updateSessionExpiry = `-- name: UpdateSessionExpiry :exec
UPDATE sessions
SET expires_at = ?
WHERE token = ?
`

type UpdateSessionExpiryParams struct {
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionExpiry, arg.ExpiresAt, arg.Token)
	return err
}
