// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package db

import (
	"context"
	"database/sql"
)

const countSuppliersByCompany = `-- name: CountSuppliersByCompany :one
SELECT COUNT(*) FROM suppliers
WHERE company_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountSuppliersByCompany(ctx context.Context, companyID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSuppliersByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
  company_id, name, address, reu_code, contacts,
  created_by, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, name, address, reu_code, contacts, company_id, created_by, created_at, updated_at, deleted_at
`

type CreateSupplierParams struct {
	CompanyID sql.NullInt64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CreatedBy sql.NullInt64
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier,
		arg.CompanyID,
		arg.Name,
		arg.Address,
		arg.ReuCode,
		arg.Contacts,
		arg.CreatedBy,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
UPDATE suppliers
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type DeleteSupplierParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) error {
	_, err := q.db.ExecContext(ctx, deleteSupplier, arg.ID, arg.CompanyID)
	return err
}

const getSupplierByID = `-- name: GetSupplierByID :one

SELECT id, company_id, name, address, reu_code, contacts,
       created_by, created_at, updated_at
FROM suppliers
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetSupplierByIDParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

type GetSupplierByIDRow struct {
	ID        int64
	CompanyID sql.NullInt64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

// ============================================================
// suppliers queries
// ============================================================
func (q *Queries) GetSupplierByID(ctx context.Context, arg GetSupplierByIDParams) (GetSupplierByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSupplierByID, arg.ID, arg.CompanyID)
	var i GetSupplierByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByIDWithCompany = `-- name: GetSupplierByIDWithCompany :one
SELECT id, company_id, name, address, reu_code, contacts,
       created_by, created_at, updated_at
FROM suppliers
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetSupplierByIDWithCompanyParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

type GetSupplierByIDWithCompanyRow struct {
	ID        int64
	CompanyID sql.NullInt64
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	CreatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetSupplierByIDWithCompany(ctx context.Context, arg GetSupplierByIDWithCompanyParams) (GetSupplierByIDWithCompanyRow, error) {
	row := q.db.QueryRowContext(ctx, getSupplierByIDWithCompany, arg.ID, arg.CompanyID)
	var i GetSupplierByIDWithCompanyRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierName = `-- name: GetSupplierName :one
SELECT name FROM suppliers
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetSupplierNameParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) GetSupplierName(ctx context.Context, arg GetSupplierNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSupplierName, arg.ID, arg.CompanyID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listSuppliersByCompany = `-- name: ListSuppliersByCompany :many
SELECT id, name, address, reu_code, contacts
FROM suppliers
WHERE company_id = ? AND deleted_at IS NULL
ORDER BY name
`

type ListSuppliersByCompanyRow struct {
	ID       int64
	Name     string
	Address  sql.NullString
	ReuCode  sql.NullString
	Contacts sql.NullString
}

func (q *Queries) ListSuppliersByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListSuppliersByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listSuppliersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuppliersByCompanyRow
	for rows.Next() {
		var i ListSuppliersByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ReuCode,
			&i.Contacts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supplierExists = `-- name: SupplierExists :one
SELECT COUNT(*) FROM suppliers
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type SupplierExistsParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) SupplierExists(ctx context.Context, arg SupplierExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, supplierExists, arg.ID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = ?, address = ?, reu_code = ?, contacts = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
RETURNING id, name, address, reu_code, contacts, company_id, created_by, created_at, updated_at, deleted_at
`

type UpdateSupplierParams struct {
	Name      string
	Address   sql.NullString
	ReuCode   sql.NullString
	Contacts  sql.NullString
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, updateSupplier,
		arg.Name,
		arg.Address,
		arg.ReuCode,
		arg.Contacts,
		arg.ID,
		arg.CompanyID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ReuCode,
		&i.Contacts,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
