// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplements.sql

package db

import (
	"context"
	"database/sql"
)

const countSupplementsByContract = `-- name: CountSupplementsByContract :one
SELECT COUNT(*) FROM supplements
WHERE contract_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountSupplementsByContract(ctx context.Context, contractID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSupplementsByContract, contractID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplement = `-- name: CreateSupplement :one
INSERT INTO supplements (
  contract_id, supplement_number, description, effective_date,
  modifications, status, client_signer_id, supplier_signer_id,
  internal_id, company_id, created_by, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, contract_id, supplement_number, description, effective_date, modifications, status, client_signer_id, supplier_signer_id, internal_id, company_id, modification_type, deleted_at, created_by, created_at, updated_at
`

type CreateSupplementParams struct {
	ContractID       int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Modifications    sql.NullString
	Status           string
	ClientSignerID   sql.NullInt64
	SupplierSignerID sql.NullInt64
	InternalID       sql.NullString
	CompanyID        sql.NullInt64
	CreatedBy        sql.NullInt64
}

func (q *Queries) CreateSupplement(ctx context.Context, arg CreateSupplementParams) (Supplement, error) {
	row := q.db.QueryRowContext(ctx, createSupplement,
		arg.ContractID,
		arg.SupplementNumber,
		arg.Description,
		arg.EffectiveDate,
		arg.Modifications,
		arg.Status,
		arg.ClientSignerID,
		arg.SupplierSignerID,
		arg.InternalID,
		arg.CompanyID,
		arg.CreatedBy,
	)
	var i Supplement
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.SupplementNumber,
		&i.Description,
		&i.EffectiveDate,
		&i.Modifications,
		&i.Status,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.InternalID,
		&i.CompanyID,
		&i.ModificationType,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupplement = `-- name: DeleteSupplement :exec
UPDATE supplements
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
`

type DeleteSupplementParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) DeleteSupplement(ctx context.Context, arg DeleteSupplementParams) error {
	_, err := q.db.ExecContext(ctx, deleteSupplement, arg.ID, arg.CompanyID)
	return err
}

const getActiveSupplements = `-- name: GetActiveSupplements :many
SELECT id, supplement_number, description, effective_date, status
FROM supplements
WHERE contract_id = ? AND deleted_at IS NULL AND status = 'active'
ORDER BY effective_date ASC
`

type GetActiveSupplementsRow struct {
	ID               int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Status           string
}

func (q *Queries) GetActiveSupplements(ctx context.Context, contractID int64) ([]GetActiveSupplementsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSupplements, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSupplementsRow
	for rows.Next() {
		var i GetActiveSupplementsRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplementNumber,
			&i.Description,
			&i.EffectiveDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSupplementNumber = `-- name: GetLatestSupplementNumber :one
SELECT supplement_number
FROM supplements
WHERE contract_id = ? AND deleted_at IS NULL
ORDER BY supplement_number DESC
LIMIT 1
`

func (q *Queries) GetLatestSupplementNumber(ctx context.Context, contractID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestSupplementNumber, contractID)
	var supplement_number int64
	err := row.Scan(&supplement_number)
	return supplement_number, err
}

const getMaxSupplementInternalID = `-- name: GetMaxSupplementInternalID :one
SELECT MAX(CAST(SUBSTR(internal_id, 10) AS INTEGER))
FROM supplements
WHERE internal_id LIKE 'SPL-' || ? || '-%' AND company_id = ?
`

type GetMaxSupplementInternalIDParams struct {
	Column1   sql.NullString
	CompanyID sql.NullInt64
}

func (q *Queries) GetMaxSupplementInternalID(ctx context.Context, arg GetMaxSupplementInternalIDParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxSupplementInternalID, arg.Column1, arg.CompanyID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getSupplementByID = `-- name: GetSupplementByID :one

SELECT
  id, contract_id, supplement_number, description, effective_date,
  modifications, status, client_signer_id, supplier_signer_id,
  internal_id, company_id, created_by, created_at, updated_at
FROM supplements
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetSupplementByIDParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

type GetSupplementByIDRow struct {
	ID               int64
	ContractID       int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Modifications    sql.NullString
	Status           string
	ClientSignerID   sql.NullInt64
	SupplierSignerID sql.NullInt64
	InternalID       sql.NullString
	CompanyID        sql.NullInt64
	CreatedBy        sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

// ============================================================
// supplements queries
// ============================================================
func (q *Queries) GetSupplementByID(ctx context.Context, arg GetSupplementByIDParams) (GetSupplementByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSupplementByID, arg.ID, arg.CompanyID)
	var i GetSupplementByIDRow
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.SupplementNumber,
		&i.Description,
		&i.EffectiveDate,
		&i.Modifications,
		&i.Status,
		&i.ClientSignerID,
		&i.SupplierSignerID,
		&i.InternalID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplementStatus = `-- name: GetSupplementStatus :one
SELECT status FROM supplements
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
LIMIT 1
`

type GetSupplementStatusParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) GetSupplementStatus(ctx context.Context, arg GetSupplementStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSupplementStatus, arg.ID, arg.CompanyID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listSupplementsByCompany = `-- name: ListSupplementsByCompany :many
SELECT
  id, internal_id, contract_id, supplement_number, description,
  effective_date, modifications, modification_type, status,
  client_signer_id, supplier_signer_id, created_at, updated_at
FROM supplements
WHERE deleted_at IS NULL AND company_id = ?
ORDER BY created_at DESC
`

type ListSupplementsByCompanyRow struct {
	ID               int64
	InternalID       sql.NullString
	ContractID       int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Modifications    sql.NullString
	ModificationType sql.NullString
	Status           string
	ClientSignerID   sql.NullInt64
	SupplierSignerID sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) ListSupplementsByCompany(ctx context.Context, companyID sql.NullInt64) ([]ListSupplementsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplementsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplementsByCompanyRow
	for rows.Next() {
		var i ListSupplementsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.ContractID,
			&i.SupplementNumber,
			&i.Description,
			&i.EffectiveDate,
			&i.Modifications,
			&i.ModificationType,
			&i.Status,
			&i.ClientSignerID,
			&i.SupplierSignerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplementsByContract = `-- name: ListSupplementsByContract :many
SELECT
  id, supplement_number, description, effective_date, status, created_at
FROM supplements
WHERE contract_id = ? AND deleted_at IS NULL
ORDER BY supplement_number DESC
`

type ListSupplementsByContractRow struct {
	ID               int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Status           string
	CreatedAt        sql.NullTime
}

func (q *Queries) ListSupplementsByContract(ctx context.Context, contractID int64) ([]ListSupplementsByContractRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplementsByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplementsByContractRow
	for rows.Next() {
		var i ListSupplementsByContractRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplementNumber,
			&i.Description,
			&i.EffectiveDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supplementExists = `-- name: SupplementExists :one
SELECT COUNT(*) FROM supplements
WHERE id = ? AND company_id = ? AND deleted_at IS NULL
`

type SupplementExistsParams struct {
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) SupplementExists(ctx context.Context, arg SupplementExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, supplementExists, arg.ID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSupplement = `-- name: UpdateSupplement :exec
UPDATE supplements
SET contract_id = ?, supplement_number = ?, description = ?,
    effective_date = ?, modifications = ?, modification_type = ?,
    status = ?, client_signer_id = ?, supplier_signer_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
`

type UpdateSupplementParams struct {
	ContractID       int64
	SupplementNumber int64
	Description      sql.NullString
	EffectiveDate    sql.NullTime
	Modifications    sql.NullString
	ModificationType sql.NullString
	Status           string
	ClientSignerID   sql.NullInt64
	SupplierSignerID sql.NullInt64
	ID               int64
	CompanyID        sql.NullInt64
}

func (q *Queries) UpdateSupplement(ctx context.Context, arg UpdateSupplementParams) error {
	_, err := q.db.ExecContext(ctx, updateSupplement,
		arg.ContractID,
		arg.SupplementNumber,
		arg.Description,
		arg.EffectiveDate,
		arg.Modifications,
		arg.ModificationType,
		arg.Status,
		arg.ClientSignerID,
		arg.SupplierSignerID,
		arg.ID,
		arg.CompanyID,
	)
	return err
}

const updateSupplementStatus = `-- name: UpdateSupplementStatus :exec
UPDATE supplements
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL AND company_id = ?
`

type UpdateSupplementStatusParams struct {
	Status    string
	ID        int64
	CompanyID sql.NullInt64
}

func (q *Queries) UpdateSupplementStatus(ctx context.Context, arg UpdateSupplementStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSupplementStatus, arg.Status, arg.ID, arg.CompanyID)
	return err
}
