// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSetting = `-- name: DeleteSetting :exec
UPDATE system_settings
SET deleted_at = CURRENT_TIMESTAMP
WHERE key = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const getAllSettings = `-- name: GetAllSettings :many
SELECT id, key, value, category, updated_by, updated_at
FROM system_settings
WHERE deleted_at IS NULL
ORDER BY category, key
`

type GetAllSettingsRow struct {
	ID        int64
	Key       string
	Value     sql.NullString
	Category  string
	UpdatedBy sql.NullInt64
	UpdatedAt sql.NullTime
}

func (q *Queries) GetAllSettings(ctx context.Context) ([]GetAllSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSettingsRow
	for rows.Next() {
		var i GetAllSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.Category,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoolSetting = `-- name: GetBoolSetting :one
SELECT value FROM system_settings
WHERE key = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetBoolSetting(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getBoolSetting, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const getSettingValue = `-- name: GetSettingValue :one

SELECT value FROM system_settings
WHERE key = ? AND deleted_at IS NULL
LIMIT 1
`

// ============================================================
// system_settings queries
// ============================================================
// Soft-delete pattern: All SELECTs include "AND deleted_at IS NULL"
// unless explicitly fetching all (including deleted).
// ============================================================
func (q *Queries) GetSettingValue(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSettingValue, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const getSettingsByKeys = `-- name: GetSettingsByKeys :many
SELECT key, value FROM system_settings
WHERE key IN (?, ?, ?, ?)
  AND deleted_at IS NULL
`

type GetSettingsByKeysParams struct {
	Key   string
	Key_2 string
	Key_3 string
	Key_4 string
}

type GetSettingsByKeysRow struct {
	Key   string
	Value sql.NullString
}

func (q *Queries) GetSettingsByKeys(ctx context.Context, arg GetSettingsByKeysParams) ([]GetSettingsByKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, getSettingsByKeys,
		arg.Key,
		arg.Key_2,
		arg.Key_3,
		arg.Key_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSettingsByKeysRow
	for rows.Next() {
		var i GetSettingsByKeysRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSettingValue = `-- name: SetSettingValue :exec
INSERT INTO system_settings (key, value, category, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
  value = excluded.value,
  category = excluded.category,
  updated_at = CURRENT_TIMESTAMP
`

type SetSettingValueParams struct {
	Key      string
	Value    sql.NullString
	Category string
}

func (q *Queries) SetSettingValue(ctx context.Context, arg SetSettingValueParams) error {
	_, err := q.db.ExecContext(ctx, setSettingValue, arg.Key, arg.Value, arg.Category)
	return err
}

const updateSettingValue = `-- name: UpdateSettingValue :exec
UPDATE system_settings
SET value = ?, updated_by = ?, updated_at = CURRENT_TIMESTAMP
WHERE key = ? AND deleted_at IS NULL
`

type UpdateSettingValueParams struct {
	Value     sql.NullString
	UpdatedBy sql.NullInt64
	Key       string
}

func (q *Queries) UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) error {
	_, err := q.db.ExecContext(ctx, updateSettingValue, arg.Value, arg.UpdatedBy, arg.Key)
	return err
}
