// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_companies.sql

package db

import (
	"context"
)

const checkUserCompanyAccess = `-- name: CheckUserCompanyAccess :one
SELECT COUNT(*) FROM user_companies
WHERE user_id = ? AND company_id = ?
`

type CheckUserCompanyAccessParams struct {
	UserID    int64
	CompanyID int64
}

func (q *Queries) CheckUserCompanyAccess(ctx context.Context, arg CheckUserCompanyAccessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserCompanyAccess, arg.UserID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCompanyAccess = `-- name: CountUserCompanyAccess :one
SELECT COUNT(*) FROM user_companies
WHERE user_id = ? AND company_id = ? AND deleted_at IS NULL
`

type CountUserCompanyAccessParams struct {
	UserID    int64
	CompanyID int64
}

func (q *Queries) CountUserCompanyAccess(ctx context.Context, arg CountUserCompanyAccessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCompanyAccess, arg.UserID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserCompany = `-- name: CreateUserCompany :exec
INSERT INTO user_companies (user_id, company_id, is_default)
VALUES (?, ?, ?)
`

type CreateUserCompanyParams struct {
	UserID    int64
	CompanyID int64
	IsDefault int64
}

func (q *Queries) CreateUserCompany(ctx context.Context, arg CreateUserCompanyParams) error {
	_, err := q.db.ExecContext(ctx, createUserCompany, arg.UserID, arg.CompanyID, arg.IsDefault)
	return err
}

const getUserDefaultCompany = `-- name: GetUserDefaultCompany :one

SELECT company_id FROM user_companies
WHERE user_id = ? AND is_default = 1
`

// ============================================================
// user_companies queries
// ============================================================
func (q *Queries) GetUserDefaultCompany(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserDefaultCompany, userID)
	var company_id int64
	err := row.Scan(&company_id)
	return company_id, err
}

const resetUserDefaultCompanies = `-- name: ResetUserDefaultCompanies :exec
UPDATE user_companies SET is_default = 0
WHERE user_id = ?
`

func (q *Queries) ResetUserDefaultCompanies(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, resetUserDefaultCompanies, userID)
	return err
}

const setDefaultCompany = `-- name: SetDefaultCompany :exec
UPDATE user_companies SET is_default = 1
WHERE user_id = ? AND company_id = ?
`

type SetDefaultCompanyParams struct {
	UserID    int64
	CompanyID int64
}

func (q *Queries) SetDefaultCompany(ctx context.Context, arg SetDefaultCompanyParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultCompany, arg.UserID, arg.CompanyID)
	return err
}

const updateUserCompany = `-- name: UpdateUserCompany :exec
UPDATE user_companies SET company_id = ?, is_default = 1
WHERE user_id = ?
`

type UpdateUserCompanyParams struct {
	CompanyID int64
	UserID    int64
}

func (q *Queries) UpdateUserCompany(ctx context.Context, arg UpdateUserCompanyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCompany, arg.CompanyID, arg.UserID)
	return err
}

const userCompanyExists = `-- name: UserCompanyExists :one
SELECT COUNT(*) FROM user_companies
WHERE user_id = ? AND company_id = ?
`

type UserCompanyExistsParams struct {
	UserID    int64
	CompanyID int64
}

func (q *Queries) UserCompanyExists(ctx context.Context, arg UserCompanyExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userCompanyExists, arg.UserID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
