// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAvatarFields = `-- name: GetAvatarFields :one
SELECT avatar_url, avatar_key
FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetAvatarFieldsRow struct {
	AvatarUrl sql.NullString
	AvatarKey sql.NullString
}

func (q *Queries) GetAvatarFields(ctx context.Context, id int64) (GetAvatarFieldsRow, error) {
	row := q.db.QueryRowContext(ctx, getAvatarFields, id)
	var i GetAvatarFieldsRow
	err := row.Scan(&i.AvatarUrl, &i.AvatarKey)
	return i, err
}

const getBasicUserByEmail = `-- name: GetBasicUserByEmail :one
SELECT id, name, email, role, status, company_id
FROM users
WHERE email = ? AND deleted_at IS NULL
LIMIT 1
`

type GetBasicUserByEmailRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Status    string
	CompanyID sql.NullInt64
}

func (q *Queries) GetBasicUserByEmail(ctx context.Context, email string) (GetBasicUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getBasicUserByEmail, email)
	var i GetBasicUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CompanyID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, role, status, company_id, last_access,
       setup_completed, created_at, updated_at
FROM users
WHERE email = ? AND deleted_at IS NULL
LIMIT 1
`

type GetUserByEmailRow struct {
	ID             int64
	Name           string
	Email          string
	Role           string
	Status         string
	CompanyID      sql.NullInt64
	LastAccess     sql.NullTime
	SetupCompleted sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.LastAccess,
		&i.SetupCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, name, email, role, status, company_id, last_access,
       setup_completed, created_at, updated_at
FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetUserByIDRow struct {
	ID             int64
	Name           string
	Email          string
	Role           string
	Status         string
	CompanyID      sql.NullInt64
	LastAccess     sql.NullTime
	SetupCompleted sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

// ============================================================
// users queries
// ============================================================
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.LastAccess,
		&i.SetupCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCompanyID = `-- name: GetUserCompanyID :one
SELECT company_id FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserCompanyID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getUserCompanyID, id)
	var company_id sql.NullInt64
	err := row.Scan(&company_id)
	return company_id, err
}

const getUserCompanyIDUnscoped = `-- name: GetUserCompanyIDUnscoped :one
SELECT company_id FROM users WHERE id = ?
`

func (q *Queries) GetUserCompanyIDUnscoped(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getUserCompanyIDUnscoped, id)
	var company_id sql.NullInt64
	err := row.Scan(&company_id)
	return company_id, err
}

const getUserForSignIn = `-- name: GetUserForSignIn :one
SELECT id, password_hash, role, status, company_id, setup_completed
FROM users
WHERE email = ? AND deleted_at IS NULL
LIMIT 1
`

type GetUserForSignInRow struct {
	ID             int64
	PasswordHash   string
	Role           string
	Status         string
	CompanyID      sql.NullInt64
	SetupCompleted sql.NullBool
}

func (q *Queries) GetUserForSignIn(ctx context.Context, email string) (GetUserForSignInRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForSignIn, email)
	var i GetUserForSignInRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.SetupCompleted,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserRole(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUsersByCompany = `-- name: GetUsersByCompany :many
SELECT id, name, email, role, status
FROM users
WHERE company_id = ? AND deleted_at IS NULL
ORDER BY name
`

type GetUsersByCompanyRow struct {
	ID     int64
	Name   string
	Email  string
	Role   string
	Status string
}

func (q *Queries) GetUsersByCompany(ctx context.Context, companyID sql.NullInt64) ([]GetUsersByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByCompanyRow
	for rows.Next() {
		var i GetUsersByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAdminEmails = `-- name: ListActiveAdminEmails :many
SELECT email FROM users
WHERE role = 'admin' AND status = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) ListActiveAdminEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAdminEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, email, role, status, company_id
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListAllUsersRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Status    string
	CompanyID sql.NullInt64
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = ?, email = ?, role = ?, status = ?,
    company_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Name      string
	Email     string
	Role      string
	Status    string
	CompanyID sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.CompanyID,
		arg.ID,
	)
	return err
}

const updateUserLastAccess = `-- name: UpdateUserLastAccess :exec
UPDATE users
SET last_access = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastAccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastAccess, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}

const updateUserURLFields = `-- name: UpdateUserURLFields :exec
UPDATE users
SET avatar_url = ?, avatar_key = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserURLFieldsParams struct {
	AvatarUrl sql.NullString
	AvatarKey sql.NullString
	ID        int64
}

func (q *Queries) UpdateUserURLFields(ctx context.Context, arg UpdateUserURLFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserURLFields, arg.AvatarUrl, arg.AvatarKey, arg.ID)
	return err
}

const userExists = `-- name: UserExists :one
SELECT COUNT(*) FROM users
WHERE email = ? AND deleted_at IS NULL
`

func (q *Queries) UserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}
